import {
  mkdirSync,
  writeFileSync,
} from "node:fs";

import {
  homedir,
} from "node:os";

import {
  join,
} from "node:path";

export function installOpenCodePlugin(
  options: {
    directory?: string;
    binary?: string;
  } = {},
): string {
  const directory =
    options.directory ??
    join(
      homedir(),
      ".config",
      "opencode",
      "plugins",
    );

  mkdirSync(
    directory,
    {
      recursive: true,
    },
  );

  const target =
    join(
      directory,
      "toolnet-memory.js",
    );

  const binary =
    options.binary ??
    process.env
      .TOOLNET_MEMORY_BIN ??
    "toolnet-memory";

  const content =
`// Generated by ToolNet Memory.
// Native OpenCode lifecycle → ToolNet session sync.

function getSessionId(event) {
  const p = event?.properties ?? {}

  const candidates = [
    p.sessionID,
    p.sessionId,
    p.info?.id,
    p.session?.id,
  ]

  return candidates.find(
    value => typeof value === "string" && value.length > 0
  ) ?? null
}

export const ToolNetMemoryPlugin = async ({ directory }) => {
  const binary = ${JSON.stringify(binary)}

  function sync(sessionId, flag) {
    if (!sessionId) return

    try {
      const args = [
        binary,
        "session:opencode-sync",
        sessionId,
        "--project",
        directory,
      ]

      if (flag) {
        args.push(flag)
      }

      const child = Bun.spawn(args, {
        stdin: "ignore",
        stdout: "ignore",
        stderr: "ignore",
      })

      if (
        typeof child.unref === "function"
      ) {
        child.unref()
      }
    } catch {
      // Memory capture must never break OpenCode.
    }
  }

  return {
    event: async ({ event }) => {
      const sessionId =
        getSessionId(event)

      if (!sessionId) {
        return
      }

      if (event.type === "session.idle") {
        sync(sessionId, "--idle")
        return
      }

      if (event.type === "session.compacted") {
        sync(sessionId, "--compacted")
        return
      }

      if (event.type === "session.error") {
        sync(sessionId, "--error")
      }
    },
  }
}
`;

  writeFileSync(
    target,
    content,
    {
      encoding:
        "utf8",

      mode:
        0o600,
    },
  );

  return target;
}
