import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";

import {
  homedir,
} from "node:os";

import {
  join,
} from "node:path";

const START =
  "<!-- TOOLNET_MEMORY_BOOTSTRAP_START -->";

const END =
  "<!-- TOOLNET_MEMORY_BOOTSTRAP_END -->";

function installBootstrapInstructions() {
  const file =
    join(
      homedir(),
      ".config",
      "opencode",
      "AGENTS.md",
    );

  mkdirSync(
    join(
      homedir(),
      ".config",
      "opencode",
    ),
    {
      recursive:
        true,
    },
  );

  const block =
`${START}
## ToolNet Memory — Project Continuity

When the current workspace belongs to a ToolNet project, identified by a nearest ancestor containing \`.toolnet/project.json\`:

1. Before planning, editing, or running implementation commands, read that project root's \`.toolnet/context/startup.md\`.
2. Treat its PROJECT RULES, MISSION, CURRENT OBJECTIVE, rationale, current phase/task, Definition of Done, blockers and next actions as project continuity context.
3. Do not restart work already marked completed unless repository evidence proves it must be revisited.
4. Verify current repository state before continuing old work.
5. If \`.toolnet/context/startup.md\` is missing, run \`toolnet-memory context:sync --project <project-root>\`, then read it.
6. Never invent missing rationale. If ToolNet says a reason was not explicitly recorded, inspect the implementation or ask rather than guessing.

This applies automatically to every ToolNet-managed project.
${END}`;

  let content =
    existsSync(file)
      ? readFileSync(
          file,
          "utf8",
        )
      : "";

  const start =
    content.indexOf(
      START,
    );

  const end =
    content.indexOf(
      END,
    );

  if (
    start >= 0 &&
    end >= start
  ) {
    content =
      content.slice(
        0,
        start,
      ) +
      block +
      content.slice(
        end +
        END.length,
      );
  } else {
    content =
      content.trimEnd();

    if (
      content
    ) {
      content +=
        "\n\n";
    }

    content +=
      block;
  }

  writeFileSync(
    file,
    content.trimEnd() +
      "\n",
    {
      encoding:
        "utf8",

      mode:
        0o600,
    },
  );

  return file;
}


export function installOpenCodePlugin(
  options: {
    directory?:
      string;

    binary?:
      string;
  } = {},
): string {
  const directory =
    options.directory ??
    join(
      homedir(),
      ".config",
      "opencode",
      "plugins",
    );

  mkdirSync(
    directory,
    {
      recursive:
        true,
    },
  );

  installBootstrapInstructions();

  const target =
    join(
      directory,
      "toolnet-memory.js",
    );

  const binary =
    options.binary ??
    process.env
      .TOOLNET_MEMORY_BIN ??
    "toolnet-memory";

  const content =
`// Generated by ToolNet Memory.
// OpenCode session capture + continuity bootstrap.

function getSessionId(event) {
  const p = event?.properties ?? {}

  const candidates = [
    p.sessionID,
    p.sessionId,
    p.info?.id,
    p.session?.id,
  ]

  return candidates.find(
    value => typeof value === "string" && value.length > 0
  ) ?? null
}

export const ToolNetMemoryPlugin = async ({ directory }) => {
  const binary = ${JSON.stringify(binary)}

  async function refreshContext() {
    try {
      const child = Bun.spawn(
        [
          binary,
          "context:sync",
          "--project",
          directory,
        ],
        {
          stdin: "ignore",
          stdout: "ignore",
          stderr: "ignore",
        }
      )

      await child.exited
    } catch {
      // Context sync must never break OpenCode startup.
    }
  }

  async function readContext() {
    try {
      const child = Bun.spawn(
        [
          binary,
          "context:print",
          "--project",
          directory,
          "--tokens",
          "900",
        ],
        {
          stdin: "ignore",
          stdout: "pipe",
          stderr: "ignore",
        }
      )

      const text =
        await new Response(
          child.stdout
        ).text()

      await child.exited

      return text.trim()
    } catch {
      return ""
    }
  }

  function sync(sessionId, flag) {
    if (!sessionId) return

    try {
      const args = [
        binary,
        "session:opencode-sync",
        sessionId,
        "--project",
        directory,
      ]

      if (flag) {
        args.push(flag)
      }

      const child = Bun.spawn(args, {
        stdin: "ignore",
        stdout: "ignore",
        stderr: "ignore",
      })

      if (
        typeof child.unref === "function"
      ) {
        child.unref()
      }
    } catch {
      // Memory capture must never break OpenCode.
    }
  }

  /*
   * Pull the latest project brief from ToolNet remote storage
   * before the new OpenCode session starts doing work.
   */
  await refreshContext()

  return {
    event: async ({ event }) => {
      const sessionId =
        getSessionId(event)

      if (!sessionId) {
        return
      }

      if (event.type === "session.idle") {
        sync(sessionId, "--idle")
        return
      }

      if (event.type === "session.compacted") {
        sync(sessionId, "--compacted")
        return
      }

      if (event.type === "session.error") {
        sync(sessionId, "--error")
      }
    },

    /*
     * Official OpenCode compaction hook.
     * Preserve ToolNet's semantic state after context compaction.
     */
    "experimental.session.compacting": async (_input, output) => {
      const context =
        await readContext()

      if (
        context &&
        Array.isArray(
          output.context
        )
      ) {
        output.context.push(
          context
        )
      }
    },
  }
}
`;

  writeFileSync(
    target,
    content,
    {
      encoding:
        "utf8",

      mode:
        0o600,
    },
  );

  return target;
}
