import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

import { HeadBucketCommand, S3Client } from '@aws-sdk/client-s3';

import { createAiProvider } from '../ai/factory.js';

import type { AiProviderConfig, AiProviderId } from '../ai/types.js';

import { installAutoIntegrations } from './auto-integrate.js';

const CONFIG_DIR = path.join(os.homedir(), '.config', 'toolnet-memory');
const ENV_FILE = path.join(CONFIG_DIR, '.env');

type StorageProviderName = 'r2' | 's3' | 'local' | 'huggingface';

type MainMenuChoice = 'storage' | 'ai' | 'finish' | 'exit';

const KNOWN_ENV_KEYS = new Set([
  'MEMORY_STORAGE_PROVIDER',

  'R2_ACCOUNT_ID',
  'R2_BUCKET',
  'R2_ACCESS_KEY_ID',
  'R2_SECRET_ACCESS_KEY',

  'S3_ENDPOINT',
  'S3_REGION',
  'S3_BUCKET',
  'S3_ACCESS_KEY_ID',
  'S3_SECRET_ACCESS_KEY',
  'S3_FORCE_PATH_STYLE',

  'HF_NAMESPACE',
  'HF_BUCKET',
  'HF_S3_ACCESS_KEY_ID',
  'HF_S3_SECRET_ACCESS_KEY',
  'HF_URL',

  'HF_TOKEN',
  'HF_EMBEDDING_MODEL',

  'TOOLNET_LLM_PROVIDER',
  'TOOLNET_LLM_API_KEY',
  'TOOLNET_LLM_BASE_URL',
  'TOOLNET_LLM_MODEL',
  'TOOLNET_LLM_ACCOUNT_ID',

  'TOOLNET_EMBEDDING_PROVIDER',
  'TOOLNET_EMBEDDING_API_KEY',
  'TOOLNET_EMBEDDING_BASE_URL',
  'TOOLNET_EMBEDDING_MODEL',
  'TOOLNET_EMBEDDING_ACCOUNT_ID',

  'MEMORY_LOCAL_STORAGE_PATH',
  'MEMORY_LOCAL_CACHE_MB',

  'MEMORY_AUTO_CAPTURE',
  'MEMORY_AUTO_RETRIEVE',
  'MEMORY_AUTO_SUMMARIZE',
  'MEMORY_AUTO_SYNC',

  'MEMORY_MAX_CANDIDATES',
  'MEMORY_RERANK_TOP',
  'MEMORY_FINAL_CONTEXT',
  'MEMORY_TOKEN_BUDGET',

  'TOOLNET_SESSION_LEARNING',
  'TOOLNET_WORK_CONTINUITY',
  'TOOLNET_SEMANTIC_CONTINUITY',
  'TOOLNET_SMART_HANDOFF',
]);

function parseEnv(text: string): Map<string, string> {
  const values = new Map<string, string>();

  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();

    if (!line || line.startsWith('#')) {
      continue;
    }

    const index = line.indexOf('=');

    if (index === -1) {
      continue;
    }

    const key = line.slice(0, index).trim();
    const value = line.slice(index + 1).trim();

    if (key) {
      values.set(key, value);
    }
  }

  return values;
}

function providerFrom(values: Map<string, string>): StorageProviderName {
  const explicit = values.get('MEMORY_STORAGE_PROVIDER')?.trim();

  if (
    explicit === 'r2' ||
    explicit === 's3' ||
    explicit === 'local' ||
    explicit === 'huggingface'
  ) {
    return explicit;
  }

  if (values.get('R2_ACCOUNT_ID') && values.get('R2_BUCKET')) {
    return 'r2';
  }

  if (values.get('S3_BUCKET')) {
    return 's3';
  }

  if (values.get('HF_BUCKET') && values.get('HF_S3_ACCESS_KEY_ID')) {
    return 'huggingface';
  }

  if (values.get('MEMORY_LOCAL_STORAGE_PATH')) {
    return 'local';
  }

  return 'r2';
}

function providerLabel(provider: StorageProviderName): string {
  switch (provider) {
    case 'r2':
      return 'Cloudflare R2';

    case 's3':
      return 'S3 / S3-compatible';

    case 'huggingface':
      return 'Hugging Face S3';

    case 'local':
      return 'Local';

    default:
      return provider;
  }
}

function requiredFor(provider: StorageProviderName): string[] {
  switch (provider) {
    case 'r2':
      return ['R2_ACCOUNT_ID', 'R2_BUCKET', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY'];

    case 's3':
      return ['S3_BUCKET', 'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY'];

    case 'huggingface':
      return ['HF_BUCKET', 'HF_S3_ACCESS_KEY_ID', 'HF_S3_SECRET_ACCESS_KEY'];

    case 'local':
      return [];

    default:
      return [];
  }
}

function storageConfigured(values: Map<string, string>): boolean {
  const provider = providerFrom(values);

  if (provider === 'local') {
    return true;
  }

  return requiredFor(provider).every((key) => Boolean(values.get(key)?.trim()));
}

function masked(value: string | undefined): string {
  if (!value) {
    return 'not configured';
  }

  if (value.length <= 8) {
    return 'configured';
  }

  return `${value.slice(0, 4)}••••${value.slice(-3)}`;
}

function renderEnv(values: Map<string, string>): string {
  const provider = providerFrom(values);

  const lines = [
    '# ==========================================================',
    '# TOOLNET MEMORY',
    '# Generated by: toolnet-memory setup',
    '# Do not commit this file.',
    '# ==========================================================',
    '',
    `MEMORY_STORAGE_PROVIDER=${provider}`,
    '',
    '# ----------------------------------------------------------',
    '# Cloudflare R2',
    '# ----------------------------------------------------------',
    `R2_ACCOUNT_ID=${values.get('R2_ACCOUNT_ID') ?? ''}`,
    `R2_BUCKET=${values.get('R2_BUCKET') ?? 'toolnet-memory'}`,
    `R2_ACCESS_KEY_ID=${values.get('R2_ACCESS_KEY_ID') ?? ''}`,
    `R2_SECRET_ACCESS_KEY=${values.get('R2_SECRET_ACCESS_KEY') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# Generic S3 / S3-compatible',
    '# ----------------------------------------------------------',
    `S3_ENDPOINT=${values.get('S3_ENDPOINT') ?? ''}`,
    `S3_REGION=${values.get('S3_REGION') ?? 'us-east-1'}`,
    `S3_BUCKET=${values.get('S3_BUCKET') ?? 'toolnet-memory'}`,
    `S3_ACCESS_KEY_ID=${values.get('S3_ACCESS_KEY_ID') ?? ''}`,
    `S3_SECRET_ACCESS_KEY=${values.get('S3_SECRET_ACCESS_KEY') ?? ''}`,
    `S3_FORCE_PATH_STYLE=${values.get('S3_FORCE_PATH_STYLE') ?? 'false'}`,
    '',
    '# ----------------------------------------------------------',
    '# Hugging Face S3',
    '# ----------------------------------------------------------',
    `HF_NAMESPACE=${values.get('HF_NAMESPACE') ?? ''}`,
    `HF_BUCKET=${values.get('HF_BUCKET') ?? 'toolnet-memory'}`,
    `HF_S3_ACCESS_KEY_ID=${values.get('HF_S3_ACCESS_KEY_ID') ?? ''}`,
    `HF_S3_SECRET_ACCESS_KEY=${values.get('HF_S3_SECRET_ACCESS_KEY') ?? ''}`,
    `HF_URL=${values.get('HF_URL') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# AI / LLM - canonical ToolNet configuration',
    '# ----------------------------------------------------------',
    `TOOLNET_LLM_PROVIDER=${values.get('TOOLNET_LLM_PROVIDER') ?? ''}`,
    `TOOLNET_LLM_API_KEY=${values.get('TOOLNET_LLM_API_KEY') ?? ''}`,
    `TOOLNET_LLM_BASE_URL=${values.get('TOOLNET_LLM_BASE_URL') ?? ''}`,
    `TOOLNET_LLM_MODEL=${values.get('TOOLNET_LLM_MODEL') ?? ''}`,
    `TOOLNET_LLM_ACCOUNT_ID=${values.get('TOOLNET_LLM_ACCOUNT_ID') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# Embedding - canonical ToolNet configuration',
    '# ----------------------------------------------------------',
    `TOOLNET_EMBEDDING_PROVIDER=${values.get('TOOLNET_EMBEDDING_PROVIDER') ?? ''}`,
    `TOOLNET_EMBEDDING_API_KEY=${values.get('TOOLNET_EMBEDDING_API_KEY') ?? ''}`,
    `TOOLNET_EMBEDDING_BASE_URL=${values.get('TOOLNET_EMBEDDING_BASE_URL') ?? ''}`,
    `TOOLNET_EMBEDDING_MODEL=${values.get('TOOLNET_EMBEDDING_MODEL') ?? ''}`,
    `TOOLNET_EMBEDDING_ACCOUNT_ID=${values.get('TOOLNET_EMBEDDING_ACCOUNT_ID') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# Embedding - legacy/current compatibility',
    '# ----------------------------------------------------------',
    `HF_TOKEN=${values.get('HF_TOKEN') ?? ''}`,
    `HF_EMBEDDING_MODEL=${
      values.get('HF_EMBEDDING_MODEL') ?? 'sentence-transformers/all-MiniLM-L6-v2'
    }`,
    '',
    '# ----------------------------------------------------------',
    '# Local storage/cache',
    '# ----------------------------------------------------------',
    `MEMORY_LOCAL_STORAGE_PATH=${values.get('MEMORY_LOCAL_STORAGE_PATH') ?? ''}`,
    `MEMORY_LOCAL_CACHE_MB=${values.get('MEMORY_LOCAL_CACHE_MB') ?? '200'}`,
    '',
    '# ----------------------------------------------------------',
    '# Automation',
    '# ----------------------------------------------------------',
    `MEMORY_AUTO_CAPTURE=${values.get('MEMORY_AUTO_CAPTURE') ?? 'true'}`,
    `MEMORY_AUTO_RETRIEVE=${values.get('MEMORY_AUTO_RETRIEVE') ?? 'true'}`,
    `MEMORY_AUTO_SUMMARIZE=${values.get('MEMORY_AUTO_SUMMARIZE') ?? 'true'}`,
    `MEMORY_AUTO_SYNC=${values.get('MEMORY_AUTO_SYNC') ?? 'true'}`,
    '',
    '# ----------------------------------------------------------',
    '# Retrieval',
    '# ----------------------------------------------------------',
    `MEMORY_MAX_CANDIDATES=${values.get('MEMORY_MAX_CANDIDATES') ?? '50'}`,
    `MEMORY_RERANK_TOP=${values.get('MEMORY_RERANK_TOP') ?? '10'}`,
    `MEMORY_FINAL_CONTEXT=${values.get('MEMORY_FINAL_CONTEXT') ?? '5'}`,
    `MEMORY_TOKEN_BUDGET=${values.get('MEMORY_TOKEN_BUDGET') ?? '2000'}`,
    '',
    '# ----------------------------------------------------------',
    '# Automatic Session Memory',
    '# ----------------------------------------------------------',
    `TOOLNET_SESSION_LEARNING=${values.get('TOOLNET_SESSION_LEARNING') ?? '1'}`,
    `TOOLNET_WORK_CONTINUITY=${values.get('TOOLNET_WORK_CONTINUITY') ?? '1'}`,
    `TOOLNET_SEMANTIC_CONTINUITY=${values.get('TOOLNET_SEMANTIC_CONTINUITY') ?? '1'}`,
    `TOOLNET_SMART_HANDOFF=${values.get('TOOLNET_SMART_HANDOFF') ?? '1'}`,
  ];

  const unknown = [...values.entries()].filter(([key]) => !KNOWN_ENV_KEYS.has(key));

  if (unknown.length > 0) {
    lines.push(
      '',
      '# ----------------------------------------------------------',
      '# Preserved settings',
      '# ----------------------------------------------------------'
    );

    for (const [key, value] of unknown) {
      lines.push(`${key}=${value}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function saveEnv(values: Map<string, string>): void {
  fs.mkdirSync(CONFIG_DIR, {
    recursive: true,
    mode: 0o700,
  });

  const temp = `${ENV_FILE}.tmp-${process.pid}`;

  fs.writeFileSync(temp, renderEnv(values), {
    encoding: 'utf8',
    mode: 0o600,
  });

  fs.renameSync(temp, ENV_FILE);

  fs.chmodSync(CONFIG_DIR, 0o700);
  fs.chmodSync(ENV_FILE, 0o600);
}

function setIfEntered(
  values: Map<string, string>,
  key: string,
  value: string,
  fallback?: string
): void {
  const normalized = value.trim();

  if (normalized) {
    values.set(key, normalized);
    return;
  }

  if (!values.get(key) && fallback !== undefined) {
    values.set(key, fallback);
  }
}

async function secretQuestion(rl: readline.Interface, label: string): Promise<string> {
  if (!input.isTTY) {
    return '';
  }

  rl.pause();

  output.write(label);

  return new Promise((resolve) => {
    let value = '';
    let finished = false;

    const finish = () => {
      if (finished) {
        return;
      }

      finished = true;

      input.off('data', onData);
      input.setRawMode?.(false);
      input.pause();

      output.write('\n');

      rl.resume();

      resolve(value);
    };

    const onData = (chunk: Buffer) => {
      for (const ch of chunk.toString('utf8')) {
        if (ch === '\r' || ch === '\n') {
          finish();
          return;
        }

        if (ch === '\u0003') {
          input.off('data', onData);
          input.setRawMode?.(false);
          output.write('\n');
          process.exit(130);
        }

        if (ch === '\u007f') {
          value = value.slice(0, -1);
          continue;
        }

        value += ch;
      }
    };

    input.resume();
    input.setRawMode?.(true);
    input.on('data', onData);
  });
}

type StorageTestResult = {
  ok: boolean;
  message: string;
};

function normalizeEndpoint(value: string): string {
  return value.trim().replace(/\/+$/, '');
}

function r2Endpoint(accountId: string): string {
  return `https://${accountId}.r2.cloudflarestorage.com`;
}

async function testS3Connection(options: {
  endpoint?: string;
  region: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  forcePathStyle?: boolean;
}): Promise<StorageTestResult> {
  const controller = new AbortController();

  const timeout = setTimeout(() => controller.abort(), 15000);

  timeout.unref?.();

  const client = new S3Client({
    region: options.region,
    endpoint: options.endpoint || undefined,
    forcePathStyle: options.forcePathStyle ?? false,
    credentials: {
      accessKeyId: options.accessKeyId,
      secretAccessKey: options.secretAccessKey,
    },
  });

  try {
    await client.send(
      new HeadBucketCommand({
        Bucket: options.bucket,
      }),
      {
        abortSignal: controller.signal,
      }
    );

    return {
      ok: true,
      message: `Bucket "${options.bucket}" reachable`,
    };
  } catch (error) {
    return {
      ok: false,
      message: error instanceof Error ? error.message : String(error),
    };
  } finally {
    clearTimeout(timeout);
    client.destroy();
  }
}

async function testR2Storage(values: Map<string, string>): Promise<StorageTestResult> {
  const accountId = values.get('R2_ACCOUNT_ID')?.trim() ?? '';

  const bucket = values.get('R2_BUCKET')?.trim() ?? '';

  const accessKeyId = values.get('R2_ACCESS_KEY_ID')?.trim() ?? '';

  const secretAccessKey = values.get('R2_SECRET_ACCESS_KEY')?.trim() ?? '';

  if (!accountId || !bucket || !accessKeyId || !secretAccessKey) {
    return {
      ok: false,
      message: 'R2 configuration is incomplete',
    };
  }

  return testS3Connection({
    endpoint: r2Endpoint(accountId),
    region: 'auto',
    bucket,
    accessKeyId,
    secretAccessKey,
  });
}

async function testGenericS3Storage(values: Map<string, string>): Promise<StorageTestResult> {
  const endpoint = normalizeEndpoint(values.get('S3_ENDPOINT') ?? '');

  const region = values.get('S3_REGION')?.trim() || 'us-east-1';

  const bucket = values.get('S3_BUCKET')?.trim() ?? '';

  const accessKeyId = values.get('S3_ACCESS_KEY_ID')?.trim() ?? '';

  const secretAccessKey = values.get('S3_SECRET_ACCESS_KEY')?.trim() ?? '';

  if (!bucket || !accessKeyId || !secretAccessKey) {
    return {
      ok: false,
      message: 'S3 configuration is incomplete',
    };
  }

  return testS3Connection({
    endpoint: endpoint || undefined,
    region,
    bucket,
    accessKeyId,
    secretAccessKey,
    forcePathStyle: values.get('S3_FORCE_PATH_STYLE') === 'true',
  });
}

async function testHuggingFaceStorage(values: Map<string, string>): Promise<StorageTestResult> {
  const endpoint = normalizeEndpoint(values.get('HF_URL') ?? '');

  const bucket = values.get('HF_BUCKET')?.trim() ?? '';

  const accessKeyId = values.get('HF_S3_ACCESS_KEY_ID')?.trim() ?? '';

  const secretAccessKey = values.get('HF_S3_SECRET_ACCESS_KEY')?.trim() ?? '';

  if (!endpoint) {
    return {
      ok: false,
      message: 'HF_URL / S3 endpoint is required for connection test',
    };
  }

  if (!bucket || !accessKeyId || !secretAccessKey) {
    return {
      ok: false,
      message: 'Hugging Face S3 configuration is incomplete',
    };
  }

  return testS3Connection({
    endpoint,
    region: 'us-east-1',
    bucket,
    accessKeyId,
    secretAccessKey,
    forcePathStyle: true,
  });
}

async function testLocalStorage(values: Map<string, string>): Promise<StorageTestResult> {
  const storagePath =
    values.get('MEMORY_LOCAL_STORAGE_PATH')?.trim() ||
    path.join(os.homedir(), '.local', 'share', 'toolnet-memory');

  const probe = path.join(storagePath, `.toolnet-test-${process.pid}-${Date.now()}`);

  try {
    fs.mkdirSync(storagePath, {
      recursive: true,
      mode: 0o700,
    });

    fs.writeFileSync(probe, 'toolnet-memory\n', {
      encoding: 'utf8',
      mode: 0o600,
    });

    fs.unlinkSync(probe);

    return {
      ok: true,
      message: `Writable: ${storagePath}`,
    };
  } catch (error) {
    return {
      ok: false,
      message: error instanceof Error ? error.message : String(error),
    };
  }
}

async function testStorage(
  provider: StorageProviderName,
  values: Map<string, string>
): Promise<StorageTestResult> {
  switch (provider) {
    case 'r2':
      return testR2Storage(values);

    case 's3':
      return testGenericS3Storage(values);

    case 'huggingface':
      return testHuggingFaceStorage(values);

    case 'local':
      return testLocalStorage(values);
  }
}

async function showStorageTest(
  provider: StorageProviderName,
  values: Map<string, string>
): Promise<StorageTestResult> {
  console.log('');
  console.log(`Testing ${providerLabel(provider)}...`);

  const result = await testStorage(provider, values);

  if (result.ok) {
    console.log(`✓ ${result.message}`);
  } else {
    console.log('✗ Connection test failed');
    console.log(`  ${result.message}`);
  }

  console.log('');

  return result;
}

function printHeader(): void {
  console.log('');
  console.log('╔══════════════════════════════════════╗');
  console.log('║         TOOLNET MEMORY SETUP         ║');
  console.log('╚══════════════════════════════════════╝');
  console.log('');
}

function printCurrentStatus(values: Map<string, string>): void {
  const provider = providerFrom(values);

  console.log('Current configuration');
  console.log('──────────────────────────────────────');
  console.log(
    `Storage : ${providerLabel(provider)} ${storageConfigured(values) ? '✓' : '⚠ incomplete'}`
  );

  const llmProvider = values.get('TOOLNET_LLM_PROVIDER');

  const llmModel = values.get('TOOLNET_LLM_MODEL');

  const embeddingProvider = values.get('TOOLNET_EMBEDDING_PROVIDER');

  console.log(
    `LLM     : ${
      llmProvider
        ? `${aiProviderLabel(llmProvider)}${llmModel ? ` / ${llmModel}` : ''}`
        : 'not configured'
    }`
  );

  console.log(`Embedding: ${embeddingProvider || 'legacy/default'}`);
  console.log('');
}

async function mainMenu(rl: readline.Interface): Promise<MainMenuChoice> {
  console.log('Setup');
  console.log('──────────────────────────────────────');
  console.log('  1. Storage');
  console.log('  2. AI Model');
  console.log('  3. Finish & Save');
  console.log('  0. Exit without saving');
  console.log('');

  const answer = (await rl.question('Choose [1-3]: ')).trim();

  if (answer === '1') {
    return 'storage';
  }

  if (answer === '2') {
    return 'ai';
  }

  if (answer === '0') {
    return 'exit';
  }

  if (answer === '3') {
    return 'finish';
  }

  return 'finish';
}

async function chooseStorageProvider(
  rl: readline.Interface,
  current: StorageProviderName
): Promise<StorageProviderName | 'back'> {
  console.log('');
  console.log('Storage');
  console.log('──────────────────────────────────────');
  console.log(`  1. Cloudflare R2${current === 'r2' ? '  ✓ current' : ''}`);
  console.log(`  2. S3 / S3-compatible${current === 's3' ? '  ✓ current' : ''}`);
  console.log(`  3. Hugging Face S3${current === 'huggingface' ? '  ✓ current' : ''}`);
  console.log(`  4. Local${current === 'local' ? '  ✓ current' : ''}`);
  console.log('');
  console.log('  0. Back');
  console.log('');

  const answer = (await rl.question('Choose storage: ')).trim();

  if (answer === '0') {
    return 'back';
  }

  if (answer === '2') {
    return 's3';
  }

  if (answer === '3') {
    return 'huggingface';
  }

  if (answer === '4') {
    return 'local';
  }

  return 'r2';
}

async function configureR2(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  console.log('');
  console.log('Cloudflare R2');
  console.log('──────────────────────────────────────');

  const accountId = await rl.question(
    values.get('R2_ACCOUNT_ID') ? `ACCOUNT ID [${values.get('R2_ACCOUNT_ID')}]: ` : 'ACCOUNT ID: '
  );

  const access = await rl.question(
    values.get('R2_ACCESS_KEY_ID')
      ? `ACCESS KEY ID [${masked(values.get('R2_ACCESS_KEY_ID'))}]: `
      : 'ACCESS KEY ID: '
  );

  const bucket = await rl.question(`BUCKET [${values.get('R2_BUCKET') || 'toolnet-memory'}]: `);

  setIfEntered(values, 'R2_ACCOUNT_ID', accountId);

  setIfEntered(values, 'R2_ACCESS_KEY_ID', access);

  setIfEntered(values, 'R2_BUCKET', bucket, 'toolnet-memory');

  const finalAccountId = values.get('R2_ACCOUNT_ID')?.trim();

  if (finalAccountId) {
    console.log(`URL: ${r2Endpoint(finalAccountId)}`);
  }

  const secret = await secretQuestion(
    rl,
    values.get('R2_SECRET_ACCESS_KEY')
      ? 'SECRET ACCESS KEY [configured, Enter = keep]: '
      : 'SECRET ACCESS KEY: '
  );

  if (secret.trim()) {
    values.set('R2_SECRET_ACCESS_KEY', secret.trim());
  }
}

async function configureS3(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  console.log('');
  console.log('S3 / S3-compatible');
  console.log('──────────────────────────────────────');

  const endpoint = await rl.question(
    values.get('S3_ENDPOINT')
      ? `URL / ENDPOINT [${values.get('S3_ENDPOINT')}]: `
      : 'URL / ENDPOINT [blank = AWS S3]: '
  );

  const region = await rl.question(`REGION [${values.get('S3_REGION') || 'us-east-1'}]: `);

  const access = await rl.question(
    values.get('S3_ACCESS_KEY_ID')
      ? `ACCESS KEY ID [${masked(values.get('S3_ACCESS_KEY_ID'))}]: `
      : 'ACCESS KEY ID: '
  );

  const bucket = await rl.question(`BUCKET [${values.get('S3_BUCKET') || 'toolnet-memory'}]: `);

  const currentPathStyle = values.get('S3_FORCE_PATH_STYLE') === 'true';

  const pathStyle = await rl.question(`FORCE PATH STYLE [${currentPathStyle ? 'Y' : 'N'}] (y/n): `);

  if (endpoint.trim()) {
    values.set('S3_ENDPOINT', normalizeEndpoint(endpoint));
  }

  setIfEntered(values, 'S3_REGION', region, 'us-east-1');

  setIfEntered(values, 'S3_ACCESS_KEY_ID', access);

  setIfEntered(values, 'S3_BUCKET', bucket, 'toolnet-memory');

  if (pathStyle.trim()) {
    const value = pathStyle.trim().toLowerCase();

    values.set('S3_FORCE_PATH_STYLE', value === 'y' || value === 'yes' ? 'true' : 'false');
  } else if (!values.has('S3_FORCE_PATH_STYLE')) {
    values.set('S3_FORCE_PATH_STYLE', 'false');
  }

  const secret = await secretQuestion(
    rl,
    values.get('S3_SECRET_ACCESS_KEY')
      ? 'SECRET ACCESS KEY [configured, Enter = keep]: '
      : 'SECRET ACCESS KEY: '
  );

  if (secret.trim()) {
    values.set('S3_SECRET_ACCESS_KEY', secret.trim());
  }
}

async function configureHuggingFace(
  rl: readline.Interface,
  values: Map<string, string>
): Promise<void> {
  console.log('');
  console.log('Hugging Face S3');
  console.log('──────────────────────────────────────');

  const namespace = await rl.question(
    values.get('HF_NAMESPACE')
      ? `NAMESPACE [${values.get('HF_NAMESPACE')}]: `
      : 'NAMESPACE [optional]: '
  );

  const access = await rl.question(
    values.get('HF_S3_ACCESS_KEY_ID')
      ? `ACCESS KEY ID [${masked(values.get('HF_S3_ACCESS_KEY_ID'))}]: `
      : 'ACCESS KEY ID: '
  );

  const bucket = await rl.question(`BUCKET [${values.get('HF_BUCKET') || 'toolnet-memory'}]: `);

  const url = await rl.question(
    values.get('HF_URL') ? `URL [${values.get('HF_URL')}]: ` : 'URL / S3 ENDPOINT: '
  );

  setIfEntered(values, 'HF_NAMESPACE', namespace);

  setIfEntered(values, 'HF_S3_ACCESS_KEY_ID', access);

  setIfEntered(values, 'HF_BUCKET', bucket, 'toolnet-memory');

  if (url.trim()) {
    values.set('HF_URL', normalizeEndpoint(url));
  }

  const secret = await secretQuestion(
    rl,
    values.get('HF_S3_SECRET_ACCESS_KEY')
      ? 'SECRET ACCESS KEY [configured, Enter = keep]: '
      : 'SECRET ACCESS KEY: '
  );

  if (secret.trim()) {
    values.set('HF_S3_SECRET_ACCESS_KEY', secret.trim());
  }
}

async function configureLocal(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  console.log('');
  console.log('Local Storage');
  console.log('──────────────────────────────────────');

  const defaultPath =
    values.get('MEMORY_LOCAL_STORAGE_PATH') ??
    path.join(os.homedir(), '.local', 'share', 'toolnet-memory');

  const storagePath = await rl.question(`LOCAL PATH [${defaultPath}]: `);

  setIfEntered(values, 'MEMORY_LOCAL_STORAGE_PATH', storagePath, defaultPath);
}

async function storageWizard(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  const original = new Map(values);

  while (true) {
    const provider = await chooseStorageProvider(rl, providerFrom(values));

    if (provider === 'back') {
      return;
    }

    const providerSnapshot = new Map(values);

    values.set('MEMORY_STORAGE_PROVIDER', provider);

    if (provider === 'r2') {
      await configureR2(rl, values);
    } else if (provider === 's3') {
      await configureS3(rl, values);
    } else if (provider === 'huggingface') {
      await configureHuggingFace(rl, values);
    } else {
      await configureLocal(rl, values);
    }

    const missing = requiredFor(provider).filter((key) => !values.get(key)?.trim());

    if (missing.length) {
      console.log('');
      console.log('⚠ Missing required fields:');

      for (const key of missing) {
        console.log(`  - ${key}`);
      }

      console.log('');
      console.log('  1. Retry');
      console.log('  2. Save anyway');
      console.log('  3. Choose another provider');
      console.log('  4. Cancel');
      console.log('');

      const action = (await rl.question('Choose [1]: ')).trim() || '1';

      if (action === '2') {
        saveEnv(values);

        console.log('');
        console.log('⚠ Saved with incomplete configuration');
        console.log('');
        return;
      }

      if (action === '3') {
        values.clear();

        for (const [key, value] of providerSnapshot) {
          values.set(key, value);
        }

        continue;
      }

      if (action === '4') {
        values.clear();

        for (const [key, value] of original) {
          values.set(key, value);
        }

        console.log('');
        console.log('Storage changes cancelled.');
        console.log('');
        return;
      }

      continue;
    }

    const result = await showStorageTest(provider, values);

    if (result.ok) {
      saveEnv(values);

      console.log(`✓ ${providerLabel(provider)} configuration saved`);
      console.log(`  ${ENV_FILE}`);
      console.log('');

      return;
    }

    console.log('  1. Retry');
    console.log('  2. Save anyway');
    console.log('  3. Choose another provider');
    console.log('  4. Cancel');
    console.log('');

    const action = (await rl.question('Choose [1]: ')).trim() || '1';

    if (action === '2') {
      saveEnv(values);

      console.log('');
      console.log('⚠ Saved even though connection test failed');
      console.log('');

      return;
    }

    if (action === '3') {
      values.clear();

      for (const [key, value] of providerSnapshot) {
        values.set(key, value);
      }

      continue;
    }

    if (action === '4') {
      values.clear();

      for (const [key, value] of original) {
        values.set(key, value);
      }

      console.log('');
      console.log('Storage changes cancelled.');
      console.log('');

      return;
    }
  }
}

type AiWizardDefinition = {
  id: AiProviderId;
  label: string;
  baseUrl?: string;
  suggestedModel?: string;
  apiKeyRequired: boolean;
  accountIdRequired?: boolean;
  baseUrlRequired?: boolean;
};

const AI_WIZARD_PROVIDERS: readonly AiWizardDefinition[] = [
  {
    id: 'openai-compatible',
    label: 'OpenAI-compatible',
    apiKeyRequired: true,
    baseUrlRequired: true,
  },

  {
    id: 'alibaba',
    label: 'Alibaba / DashScope',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    suggestedModel: 'qwen3.6-flash',
    apiKeyRequired: true,
  },

  {
    id: 'openrouter',
    label: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyRequired: true,
  },

  {
    id: 'groq',
    label: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    apiKeyRequired: true,
  },

  {
    id: 'gemini',
    label: 'Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    suggestedModel: 'gemini-3.6-flash',
    apiKeyRequired: true,
  },

  {
    id: 'huggingface',
    label: 'Hugging Face',
    baseUrl: 'https://router.huggingface.co/v1',
    apiKeyRequired: true,
  },

  {
    id: 'ollama',
    label: 'Ollama / Local',
    baseUrl: 'http://127.0.0.1:11434/v1',
    apiKeyRequired: false,
  },

  {
    id: 'custom',
    label: 'Custom endpoint',
    apiKeyRequired: false,
    baseUrlRequired: true,
  },

  {
    id: 'cloudflare',
    label: 'Cloudflare Workers AI',
    suggestedModel: '@cf/meta/llama-3.1-8b-instruct',
    apiKeyRequired: true,
    accountIdRequired: true,
  },
] as const;

function aiProviderDefinition(id: string | undefined): AiWizardDefinition | undefined {
  return AI_WIZARD_PROVIDERS.find((provider) => provider.id === id);
}

function aiProviderLabel(id: string | undefined): string {
  return aiProviderDefinition(id)?.label ?? id ?? 'not configured';
}

function currentAiProvider(values: Map<string, string>): AiProviderId | undefined {
  const provider = values.get('TOOLNET_LLM_PROVIDER')?.trim();

  return AI_WIZARD_PROVIDERS.some((item) => item.id === provider)
    ? (provider as AiProviderId)
    : undefined;
}

async function chooseAiProvider(
  rl: readline.Interface,
  current?: AiProviderId
): Promise<AiProviderId | 'back'> {
  console.log('');
  console.log('AI Model');
  console.log('──────────────────────────────────────');

  AI_WIZARD_PROVIDERS.forEach((provider, index) => {
    console.log(`  ${index + 1}. ${provider.label}${current === provider.id ? '  ✓ current' : ''}`);
  });

  console.log('');
  console.log('  0. Back');
  console.log('');

  const answer = (await rl.question('Choose provider: ')).trim();

  if (answer === '0') {
    return 'back';
  }

  const index = Number(answer) - 1;

  if (Number.isInteger(index) && index >= 0 && index < AI_WIZARD_PROVIDERS.length) {
    return AI_WIZARD_PROVIDERS[index].id;
  }

  console.log('');
  console.log('⚠ Invalid provider selection');

  return chooseAiProvider(rl, current);
}

function aiConfigComplete(values: Map<string, string>, definition: AiWizardDefinition): boolean {
  const model = values.get('TOOLNET_LLM_MODEL')?.trim();

  if (!model) {
    return false;
  }

  if (definition.apiKeyRequired && !values.get('TOOLNET_LLM_API_KEY')?.trim()) {
    return false;
  }

  if (definition.accountIdRequired && !values.get('TOOLNET_LLM_ACCOUNT_ID')?.trim()) {
    return false;
  }

  if (definition.baseUrlRequired && !values.get('TOOLNET_LLM_BASE_URL')?.trim()) {
    return false;
  }

  return true;
}

function clearCanonicalLlm(values: Map<string, string>): void {
  values.delete('TOOLNET_LLM_API_KEY');

  values.delete('TOOLNET_LLM_BASE_URL');

  values.delete('TOOLNET_LLM_MODEL');

  values.delete('TOOLNET_LLM_ACCOUNT_ID');
}

async function configureAiProvider(
  rl: readline.Interface,
  values: Map<string, string>,
  definition: AiWizardDefinition
): Promise<void> {
  console.log('');
  console.log(definition.label);
  console.log('──────────────────────────────────────');

  const existingProvider = values.get('TOOLNET_LLM_PROVIDER');

  /*
   * Changing provider must not
   * accidentally reuse another
   * provider's endpoint/key/model.
   */
  if (existingProvider && existingProvider !== definition.id) {
    clearCanonicalLlm(values);
  }

  values.set('TOOLNET_LLM_PROVIDER', definition.id);

  if (definition.accountIdRequired) {
    const current = values.get('TOOLNET_LLM_ACCOUNT_ID');

    const accountId = await rl.question(current ? `ACCOUNT ID [${current}]: ` : 'ACCOUNT ID: ');

    setIfEntered(values, 'TOOLNET_LLM_ACCOUNT_ID', accountId);
  } else {
    values.delete('TOOLNET_LLM_ACCOUNT_ID');
  }

  if (definition.apiKeyRequired || definition.id === 'custom') {
    const currentKey = values.get('TOOLNET_LLM_API_KEY');

    const apiKey = await secretQuestion(
      rl,
      currentKey
        ? 'API KEY [configured, Enter = keep]: '
        : definition.apiKeyRequired
          ? 'API KEY: '
          : 'API KEY [optional]: '
    );

    if (apiKey.trim()) {
      values.set('TOOLNET_LLM_API_KEY', apiKey.trim());
    }
  } else {
    values.delete('TOOLNET_LLM_API_KEY');
  }

  if (definition.id !== 'cloudflare') {
    const currentBase = values.get('TOOLNET_LLM_BASE_URL');

    const defaultBase = currentBase || definition.baseUrl || '';

    const baseUrl = await rl.question(
      defaultBase
        ? `BASE URL [${defaultBase}]: `
        : definition.baseUrlRequired
          ? 'BASE URL: '
          : 'BASE URL [optional]: '
    );

    const resolvedBase = baseUrl.trim() || defaultBase;

    if (resolvedBase) {
      values.set('TOOLNET_LLM_BASE_URL', normalizeEndpoint(resolvedBase));
    } else {
      values.delete('TOOLNET_LLM_BASE_URL');
    }
  } else {
    /*
     * Cloudflare provider builds
     * /accounts/{id}/ai/run itself.
     */
    values.delete('TOOLNET_LLM_BASE_URL');
  }

  const currentModel = values.get('TOOLNET_LLM_MODEL');

  const modelDefault = currentModel || definition.suggestedModel || '';

  const model = await rl.question(modelDefault ? `MODEL [${modelDefault}]: ` : 'MODEL: ');

  const resolvedModel = model.trim() || modelDefault;

  if (resolvedModel) {
    values.set('TOOLNET_LLM_MODEL', resolvedModel);
  }
}

function aiProviderConfigFromValues(values: Map<string, string>): AiProviderConfig {
  const provider = currentAiProvider(values);

  if (!provider) {
    throw new Error('AI provider is not configured');
  }

  return {
    id: provider,

    apiKey: values.get('TOOLNET_LLM_API_KEY')?.trim() || undefined,

    baseUrl: values.get('TOOLNET_LLM_BASE_URL')?.trim() || undefined,

    model: values.get('TOOLNET_LLM_MODEL')?.trim() || undefined,

    accountId: values.get('TOOLNET_LLM_ACCOUNT_ID')?.trim() || undefined,
  };
}

async function testAiProvider(values: Map<string, string>): Promise<{
  ok: boolean;
  message: string;
}> {
  const config = aiProviderConfigFromValues(values);

  console.log('');
  console.log(`Testing ${aiProviderLabel(config.id)}...`);

  try {
    const provider = createAiProvider(config);

    const result = await provider.healthCheck();

    if (result.ok) {
      console.log(`✓ Provider reachable${result.latencyMs ? ` (${result.latencyMs} ms)` : ''}`);

      console.log(`✓ Model: ${result.model ?? config.model ?? 'configured'}`);

      console.log('');

      return {
        ok: true,
        message: result.message,
      };
    }

    console.log('✗ AI provider test failed');

    console.log(`  ${result.message}`);

    console.log('');

    return {
      ok: false,
      message: result.message,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    console.log('✗ AI provider test failed');

    console.log(`  ${message}`);

    console.log('');

    return {
      ok: false,
      message,
    };
  }
}

async function aiWizard(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  const original = new Map(values);

  while (true) {
    const selected = await chooseAiProvider(rl, currentAiProvider(values));

    if (selected === 'back') {
      return;
    }

    const definition = AI_WIZARD_PROVIDERS.find((provider) => provider.id === selected);

    if (!definition) {
      continue;
    }

    await configureAiProvider(rl, values, definition);

    if (!aiConfigComplete(values, definition)) {
      console.log('');
      console.log('⚠ AI configuration is incomplete.');
      console.log('');
      console.log('  1. Retry');
      console.log('  2. Save anyway');
      console.log('  3. Choose another provider');
      console.log('  4. Cancel');
      console.log('');

      const action = (await rl.question('Choose [1]: ')).trim() || '1';

      if (action === '2') {
        saveEnv(values);

        console.log('');
        console.log('⚠ AI configuration saved without validation');
        console.log(`  ${ENV_FILE}`);
        console.log('');

        return;
      }

      if (action === '3') {
        continue;
      }

      if (action === '4') {
        values.clear();

        for (const [key, value] of original) {
          values.set(key, value);
        }

        console.log('');
        console.log('AI changes cancelled.');
        console.log('');

        return;
      }

      continue;
    }

    const result = await testAiProvider(values);

    if (result.ok) {
      saveEnv(values);

      console.log(`✓ ${definition.label} configuration saved`);

      console.log(`  ${ENV_FILE}`);

      console.log('');

      return;
    }

    console.log('  1. Retry');
    console.log('  2. Save anyway');
    console.log('  3. Choose another provider');
    console.log('  4. Cancel');
    console.log('');

    const action = (await rl.question('Choose [1]: ')).trim() || '1';

    if (action === '2') {
      saveEnv(values);

      console.log('');
      console.log('⚠ AI configuration saved even though provider test failed');

      console.log(`  ${ENV_FILE}`);

      console.log('');

      return;
    }

    if (action === '3') {
      continue;
    }

    if (action === '4') {
      values.clear();

      for (const [key, value] of original) {
        values.set(key, value);
      }

      console.log('');
      console.log('AI changes cancelled.');
      console.log('');

      return;
    }
  }
}

function enableAutomaticAgentMemory(): void {
  try {
    const results = installAutoIntegrations();
    const installed = results.filter((item) => item.installed);

    if (installed.length === 0) {
      return;
    }

    console.log('');
    console.log('Automatic AI memory');

    for (const item of installed) {
      const name =
        item.agent === 'agy'
          ? 'Agy / Antigravity'
          : item.agent === 'opencode'
            ? 'OpenCode'
            : item.agent === 'codex'
              ? 'Codex'
              : item.agent;

      console.log(`  ✓ ${name}`);
    }
  } catch {
    // Optional integration. Setup itself must remain usable.
  }
}

function ensureDefaults(values: Map<string, string>): void {
  if (!values.has('MEMORY_STORAGE_PROVIDER')) {
    values.set('MEMORY_STORAGE_PROVIDER', providerFrom(values));
  }

  if (!values.has('MEMORY_LOCAL_CACHE_MB')) {
    values.set('MEMORY_LOCAL_CACHE_MB', '200');
  }

  if (!values.has('MEMORY_AUTO_CAPTURE')) {
    values.set('MEMORY_AUTO_CAPTURE', 'true');
  }

  if (!values.has('MEMORY_AUTO_RETRIEVE')) {
    values.set('MEMORY_AUTO_RETRIEVE', 'true');
  }

  if (!values.has('MEMORY_AUTO_SUMMARIZE')) {
    values.set('MEMORY_AUTO_SUMMARIZE', 'true');
  }

  if (!values.has('MEMORY_AUTO_SYNC')) {
    values.set('MEMORY_AUTO_SYNC', 'true');
  }

  if (!values.has('MEMORY_MAX_CANDIDATES')) {
    values.set('MEMORY_MAX_CANDIDATES', '50');
  }

  if (!values.has('MEMORY_RERANK_TOP')) {
    values.set('MEMORY_RERANK_TOP', '10');
  }

  if (!values.has('MEMORY_FINAL_CONTEXT')) {
    values.set('MEMORY_FINAL_CONTEXT', '5');
  }

  if (!values.has('MEMORY_TOKEN_BUDGET')) {
    values.set('MEMORY_TOKEN_BUDGET', '2000');
  }

  if (!values.has('TOOLNET_SESSION_LEARNING')) {
    values.set('TOOLNET_SESSION_LEARNING', '1');
  }

  if (!values.has('TOOLNET_WORK_CONTINUITY')) {
    values.set('TOOLNET_WORK_CONTINUITY', '1');
  }

  if (!values.has('TOOLNET_SEMANTIC_CONTINUITY')) {
    values.set('TOOLNET_SEMANTIC_CONTINUITY', '1');
  }

  if (!values.has('TOOLNET_SMART_HANDOFF')) {
    values.set('TOOLNET_SMART_HANDOFF', '1');
  }
}

async function nonInteractiveSetup(values: Map<string, string>, exists: boolean): Promise<void> {
  ensureDefaults(values);

  if (!exists) {
    saveEnv(values);
  }

  console.log('TOOLNET MEMORY SETUP');
  console.log('');
  console.log('Interactive terminal not detected.');
  console.log(`Config: ${ENV_FILE}`);
  console.log(`Storage: ${providerLabel(providerFrom(values))}`);
  console.log('');
  console.log('Run from an interactive terminal to configure providers:');
  console.log('  toolnet-memory setup');
}

async function main(): Promise<void> {
  const exists = fs.existsSync(ENV_FILE);

  const original = exists ? parseEnv(fs.readFileSync(ENV_FILE, 'utf8')) : new Map<string, string>();

  const values = new Map(original);

  ensureDefaults(values);

  if (!input.isTTY || !output.isTTY) {
    await nonInteractiveSetup(values, exists);
    return;
  }

  const rl = readline.createInterface({
    input,
    output,
  });

  let dirty = false;

  try {
    while (true) {
      printHeader();
      printCurrentStatus(values);

      const choice = await mainMenu(rl);

      if (choice === 'storage') {
        const before = JSON.stringify([...values.entries()]);

        await storageWizard(rl, values);

        dirty = dirty || before !== JSON.stringify([...values.entries()]);
        continue;
      }

      if (choice === 'ai') {
        const before = JSON.stringify([...values.entries()]);

        await aiWizard(rl, values);

        dirty = dirty || before !== JSON.stringify([...values.entries()]);

        continue;
      }

      if (choice === 'exit') {
        if (!dirty) {
          console.log('');
          console.log('No changes made.');
          return;
        }

        console.log('');
        const confirm = (await rl.question('Discard unsaved changes? (y/N): '))
          .trim()
          .toLowerCase();

        if (confirm === 'y' || confirm === 'yes') {
          console.log('');
          console.log('Changes discarded.');
          return;
        }

        continue;
      }

      saveEnv(values);

      console.log('');
      console.log('✓ Configuration saved');
      console.log(`  ${ENV_FILE}`);
      console.log('');
      console.log(`✓ Permissions: ${fs.statSync(ENV_FILE).mode.toString(8).slice(-3)}`);
      console.log(`✓ Storage: ${providerLabel(providerFrom(values))}`);

      if (!storageConfigured(values)) {
        console.log('⚠ Storage configuration is incomplete.');
      }

      enableAutomaticAgentMemory();

      console.log('');
      console.log('Next:');
      console.log('  toolnet-memory doctor');
      console.log('');

      return;
    }
  } finally {
    rl.close();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
