import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

import { HeadBucketCommand, S3Client } from '@aws-sdk/client-s3';

import { createAiProvider } from '../ai/factory.js';

import type { AiProviderConfig, AiProviderId } from '../ai/types.js';

import { installAutoIntegrations } from './auto-integrate.js';

const CONFIG_DIR = path.join(os.homedir(), '.config', 'toolnet-memory');
const ENV_FILE = path.join(CONFIG_DIR, '.env');

type StorageProviderName = 'r2' | 's3' | 'local' | 'huggingface';

type MainMenuChoice = 'storage' | 'ai' | 'finish' | 'exit';

const KNOWN_ENV_KEYS = new Set([
  'MEMORY_STORAGE_PROVIDER',

  'R2_ACCOUNT_ID',
  'R2_BUCKET',
  'R2_ACCESS_KEY_ID',
  'R2_SECRET_ACCESS_KEY',

  'S3_ENDPOINT',
  'S3_REGION',
  'S3_BUCKET',
  'S3_ACCESS_KEY_ID',
  'S3_SECRET_ACCESS_KEY',
  'S3_FORCE_PATH_STYLE',

  'HF_NAMESPACE',
  'HF_BUCKET',
  'HF_S3_ACCESS_KEY_ID',
  'HF_S3_SECRET_ACCESS_KEY',
  'HF_URL',

  'HF_TOKEN',
  'HF_EMBEDDING_MODEL',

  'TOOLNET_LLM_PROVIDER',
  'TOOLNET_LLM_API_KEY',
  'TOOLNET_LLM_BASE_URL',
  'TOOLNET_LLM_MODEL',
  'TOOLNET_LLM_FALLBACK_1_PROVIDER',
  'TOOLNET_LLM_FALLBACK_1_API_KEY',
  'TOOLNET_LLM_FALLBACK_1_BASE_URL',
  'TOOLNET_LLM_FALLBACK_1_MODEL',
  'TOOLNET_LLM_FALLBACK_1_ACCOUNT_ID',
  'TOOLNET_LLM_FALLBACK_2_PROVIDER',
  'TOOLNET_LLM_FALLBACK_2_API_KEY',
  'TOOLNET_LLM_FALLBACK_2_BASE_URL',
  'TOOLNET_LLM_FALLBACK_2_MODEL',
  'TOOLNET_LLM_FALLBACK_2_ACCOUNT_ID',
  'TOOLNET_LLM_FALLBACK_COOLDOWN_MS',
  'TOOLNET_LLM_MAX_RETRIES',
  'TOOLNET_LLM_ACCOUNT_ID',

  'TOOLNET_EMBEDDING_PROVIDER',
  'TOOLNET_EMBEDDING_API_KEY',
  'TOOLNET_EMBEDDING_BASE_URL',
  'TOOLNET_EMBEDDING_MODEL',
  'TOOLNET_EMBEDDING_ACCOUNT_ID',

  'MEMORY_LOCAL_STORAGE_PATH',
  'MEMORY_LOCAL_CACHE_MB',

  'MEMORY_AUTO_CAPTURE',
  'MEMORY_AUTO_RETRIEVE',
  'MEMORY_AUTO_SUMMARIZE',
  'MEMORY_AUTO_SYNC',

  'MEMORY_MAX_CANDIDATES',
  'MEMORY_RERANK_TOP',
  'MEMORY_FINAL_CONTEXT',
  'MEMORY_TOKEN_BUDGET',

  'TOOLNET_SESSION_LEARNING',
  'TOOLNET_WORK_CONTINUITY',
  'TOOLNET_SEMANTIC_CONTINUITY',
  'TOOLNET_SMART_HANDOFF',
]);

function parseEnv(text: string): Map<string, string> {
  const values = new Map<string, string>();

  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();

    if (!line || line.startsWith('#')) {
      continue;
    }

    const index = line.indexOf('=');

    if (index === -1) {
      continue;
    }

    const key = line.slice(0, index).trim();
    const value = line.slice(index + 1).trim();

    if (key) {
      values.set(key, value);
    }
  }

  return values;
}

function providerFrom(values: Map<string, string>): StorageProviderName {
  const explicit = values.get('MEMORY_STORAGE_PROVIDER')?.trim();

  if (
    explicit === 'r2' ||
    explicit === 's3' ||
    explicit === 'local' ||
    explicit === 'huggingface'
  ) {
    return explicit;
  }

  if (values.get('R2_ACCOUNT_ID') && values.get('R2_BUCKET')) {
    return 'r2';
  }

  if (values.get('S3_BUCKET')) {
    return 's3';
  }

  if (values.get('HF_BUCKET') && values.get('HF_S3_ACCESS_KEY_ID')) {
    return 'huggingface';
  }

  if (values.get('MEMORY_LOCAL_STORAGE_PATH')) {
    return 'local';
  }

  return 'r2';
}

function providerLabel(provider: StorageProviderName): string {
  switch (provider) {
    case 'r2':
      return 'Cloudflare R2';

    case 's3':
      return 'S3 / S3-compatible';

    case 'huggingface':
      return 'Hugging Face S3';

    case 'local':
      return 'Local';

    default:
      return provider;
  }
}

function requiredFor(provider: StorageProviderName): string[] {
  switch (provider) {
    case 'r2':
      return ['R2_ACCOUNT_ID', 'R2_BUCKET', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY'];

    case 's3':
      return ['S3_BUCKET', 'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY'];

    case 'huggingface':
      return ['HF_BUCKET', 'HF_S3_ACCESS_KEY_ID', 'HF_S3_SECRET_ACCESS_KEY'];

    case 'local':
      return [];

    default:
      return [];
  }
}

function storageConfigured(values: Map<string, string>): boolean {
  const provider = providerFrom(values);

  if (provider === 'local') {
    return true;
  }

  return requiredFor(provider).every((key) => Boolean(values.get(key)?.trim()));
}

function masked(value: string | undefined): string {
  if (!value) {
    return 'not configured';
  }

  if (value.length <= 8) {
    return 'configured';
  }

  return `${value.slice(0, 4)}••••${value.slice(-3)}`;
}

function renderEnv(values: Map<string, string>): string {
  const provider = providerFrom(values);

  const lines = [
    '# ==========================================================',
    '# TOOLNET MEMORY',
    '# Generated by: toolnet-memory setup',
    '# Do not commit this file.',
    '# ==========================================================',
    '',
    `MEMORY_STORAGE_PROVIDER=${provider}`,
    '',
    '# ----------------------------------------------------------',
    '# Cloudflare R2',
    '# ----------------------------------------------------------',
    `R2_ACCOUNT_ID=${values.get('R2_ACCOUNT_ID') ?? ''}`,
    `R2_BUCKET=${values.get('R2_BUCKET') ?? 'toolnet-memory'}`,
    `R2_ACCESS_KEY_ID=${values.get('R2_ACCESS_KEY_ID') ?? ''}`,
    `R2_SECRET_ACCESS_KEY=${values.get('R2_SECRET_ACCESS_KEY') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# Generic S3 / S3-compatible',
    '# ----------------------------------------------------------',
    `S3_ENDPOINT=${values.get('S3_ENDPOINT') ?? ''}`,
    `S3_REGION=${values.get('S3_REGION') ?? 'us-east-1'}`,
    `S3_BUCKET=${values.get('S3_BUCKET') ?? 'toolnet-memory'}`,
    `S3_ACCESS_KEY_ID=${values.get('S3_ACCESS_KEY_ID') ?? ''}`,
    `S3_SECRET_ACCESS_KEY=${values.get('S3_SECRET_ACCESS_KEY') ?? ''}`,
    `S3_FORCE_PATH_STYLE=${values.get('S3_FORCE_PATH_STYLE') ?? 'false'}`,
    '',
    '# ----------------------------------------------------------',
    '# Hugging Face S3',
    '# ----------------------------------------------------------',
    `HF_NAMESPACE=${values.get('HF_NAMESPACE') ?? ''}`,
    `HF_BUCKET=${values.get('HF_BUCKET') ?? 'toolnet-memory'}`,
    `HF_S3_ACCESS_KEY_ID=${values.get('HF_S3_ACCESS_KEY_ID') ?? ''}`,
    `HF_S3_SECRET_ACCESS_KEY=${values.get('HF_S3_SECRET_ACCESS_KEY') ?? ''}`,
    `HF_URL=${values.get('HF_URL') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# AI / LLM - canonical ToolNet configuration',
    '# ----------------------------------------------------------',
    `TOOLNET_LLM_PROVIDER=${values.get('TOOLNET_LLM_PROVIDER') ?? ''}`,
    `TOOLNET_LLM_API_KEY=${values.get('TOOLNET_LLM_API_KEY') ?? ''}`,
    `TOOLNET_LLM_BASE_URL=${values.get('TOOLNET_LLM_BASE_URL') ?? ''}`,
    `TOOLNET_LLM_MODEL=${values.get('TOOLNET_LLM_MODEL') ?? ''}`,
    `TOOLNET_LLM_ACCOUNT_ID=${values.get('TOOLNET_LLM_ACCOUNT_ID') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# LLM fallback chain',
    '# ----------------------------------------------------------',
    `TOOLNET_LLM_FALLBACK_1_PROVIDER=${values.get('TOOLNET_LLM_FALLBACK_1_PROVIDER') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_1_API_KEY=${values.get('TOOLNET_LLM_FALLBACK_1_API_KEY') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_1_BASE_URL=${values.get('TOOLNET_LLM_FALLBACK_1_BASE_URL') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_1_MODEL=${values.get('TOOLNET_LLM_FALLBACK_1_MODEL') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_1_ACCOUNT_ID=${values.get('TOOLNET_LLM_FALLBACK_1_ACCOUNT_ID') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_2_PROVIDER=${values.get('TOOLNET_LLM_FALLBACK_2_PROVIDER') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_2_API_KEY=${values.get('TOOLNET_LLM_FALLBACK_2_API_KEY') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_2_BASE_URL=${values.get('TOOLNET_LLM_FALLBACK_2_BASE_URL') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_2_MODEL=${values.get('TOOLNET_LLM_FALLBACK_2_MODEL') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_2_ACCOUNT_ID=${values.get('TOOLNET_LLM_FALLBACK_2_ACCOUNT_ID') ?? ''}`,
    `TOOLNET_LLM_FALLBACK_COOLDOWN_MS=${values.get('TOOLNET_LLM_FALLBACK_COOLDOWN_MS') ?? '60000'}`,
    `TOOLNET_LLM_MAX_RETRIES=${values.get('TOOLNET_LLM_MAX_RETRIES') ?? '1'}`,

    '',
    '# ----------------------------------------------------------',
    '# Embedding - canonical ToolNet configuration',
    '# ----------------------------------------------------------',
    `TOOLNET_EMBEDDING_PROVIDER=${values.get('TOOLNET_EMBEDDING_PROVIDER') ?? ''}`,
    `TOOLNET_EMBEDDING_API_KEY=${values.get('TOOLNET_EMBEDDING_API_KEY') ?? ''}`,
    `TOOLNET_EMBEDDING_BASE_URL=${values.get('TOOLNET_EMBEDDING_BASE_URL') ?? ''}`,
    `TOOLNET_EMBEDDING_MODEL=${values.get('TOOLNET_EMBEDDING_MODEL') ?? ''}`,
    `TOOLNET_EMBEDDING_ACCOUNT_ID=${values.get('TOOLNET_EMBEDDING_ACCOUNT_ID') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# Embedding - legacy/current compatibility',
    '# ----------------------------------------------------------',
    `HF_TOKEN=${values.get('HF_TOKEN') ?? ''}`,
    `HF_EMBEDDING_MODEL=${
      values.get('HF_EMBEDDING_MODEL') ?? 'sentence-transformers/all-MiniLM-L6-v2'
    }`,
    '',
    '# ----------------------------------------------------------',
    '# Local storage/cache',
    '# ----------------------------------------------------------',
    `MEMORY_LOCAL_STORAGE_PATH=${values.get('MEMORY_LOCAL_STORAGE_PATH') ?? ''}`,
    `MEMORY_LOCAL_CACHE_MB=${values.get('MEMORY_LOCAL_CACHE_MB') ?? '200'}`,
    '',
    '# ----------------------------------------------------------',
    '# Automation',
    '# ----------------------------------------------------------',
    `MEMORY_AUTO_CAPTURE=${values.get('MEMORY_AUTO_CAPTURE') ?? 'true'}`,
    `MEMORY_AUTO_RETRIEVE=${values.get('MEMORY_AUTO_RETRIEVE') ?? 'true'}`,
    `MEMORY_AUTO_SUMMARIZE=${values.get('MEMORY_AUTO_SUMMARIZE') ?? 'true'}`,
    `MEMORY_AUTO_SYNC=${values.get('MEMORY_AUTO_SYNC') ?? 'true'}`,
    '',
    '# ----------------------------------------------------------',
    '# Retrieval',
    '# ----------------------------------------------------------',
    `MEMORY_MAX_CANDIDATES=${values.get('MEMORY_MAX_CANDIDATES') ?? '50'}`,
    `MEMORY_RERANK_TOP=${values.get('MEMORY_RERANK_TOP') ?? '10'}`,
    `MEMORY_FINAL_CONTEXT=${values.get('MEMORY_FINAL_CONTEXT') ?? '5'}`,
    `MEMORY_TOKEN_BUDGET=${values.get('MEMORY_TOKEN_BUDGET') ?? '2000'}`,
    '',
    '# ----------------------------------------------------------',
    '# Automatic Session Memory',
    '# ----------------------------------------------------------',
    `TOOLNET_SESSION_LEARNING=${values.get('TOOLNET_SESSION_LEARNING') ?? '1'}`,
    `TOOLNET_WORK_CONTINUITY=${values.get('TOOLNET_WORK_CONTINUITY') ?? '1'}`,
    `TOOLNET_SEMANTIC_CONTINUITY=${values.get('TOOLNET_SEMANTIC_CONTINUITY') ?? '1'}`,
    `TOOLNET_SMART_HANDOFF=${values.get('TOOLNET_SMART_HANDOFF') ?? '1'}`,
  ];

  const unknown = [...values.entries()].filter(([key]) => !KNOWN_ENV_KEYS.has(key));

  if (unknown.length > 0) {
    lines.push(
      '',
      '# ----------------------------------------------------------',
      '# Preserved settings',
      '# ----------------------------------------------------------'
    );

    for (const [key, value] of unknown) {
      lines.push(`${key}=${value}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function saveEnv(values: Map<string, string>): void {
  fs.mkdirSync(CONFIG_DIR, {
    recursive: true,
    mode: 0o700,
  });

  const temp = `${ENV_FILE}.tmp-${process.pid}`;

  fs.writeFileSync(temp, renderEnv(values), {
    encoding: 'utf8',
    mode: 0o600,
  });

  fs.renameSync(temp, ENV_FILE);

  fs.chmodSync(CONFIG_DIR, 0o700);
  fs.chmodSync(ENV_FILE, 0o600);
}

function setIfEntered(
  values: Map<string, string>,
  key: string,
  value: string,
  fallback?: string
): void {
  const normalized = value.trim();

  if (normalized) {
    values.set(key, normalized);
    return;
  }

  if (!values.get(key) && fallback !== undefined) {
    values.set(key, fallback);
  }
}

async function secretQuestion(rl: readline.Interface, label: string): Promise<string> {
  if (!input.isTTY) {
    return '';
  }

  rl.pause();

  output.write(label);

  return new Promise((resolve) => {
    let value = '';
    let finished = false;

    const finish = () => {
      if (finished) {
        return;
      }

      finished = true;

      input.off('data', onData);
      input.setRawMode?.(false);
      input.pause();

      output.write('\n');

      rl.resume();

      resolve(value);
    };

    const onData = (chunk: Buffer) => {
      for (const ch of chunk.toString('utf8')) {
        if (ch === '\r' || ch === '\n') {
          finish();
          return;
        }

        if (ch === '\u0003') {
          input.off('data', onData);
          input.setRawMode?.(false);
          output.write('\n');
          process.exit(130);
        }

        if (ch === '\u007f') {
          value = value.slice(0, -1);
          continue;
        }

        value += ch;
      }
    };

    input.resume();
    input.setRawMode?.(true);
    input.on('data', onData);
  });
}

type StorageTestResult = {
  ok: boolean;
  message: string;
};

function normalizeEndpoint(value: string): string {
  return value.trim().replace(/\/+$/, '');
}

function r2Endpoint(accountId: string): string {
  return `https://${accountId}.r2.cloudflarestorage.com`;
}

async function testS3Connection(options: {
  endpoint?: string;
  region: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  forcePathStyle?: boolean;
}): Promise<StorageTestResult> {
  const controller = new AbortController();

  const timeout = setTimeout(() => controller.abort(), 15000);

  timeout.unref?.();

  const client = new S3Client({
    region: options.region,
    endpoint: options.endpoint || undefined,
    forcePathStyle: options.forcePathStyle ?? false,
    credentials: {
      accessKeyId: options.accessKeyId,
      secretAccessKey: options.secretAccessKey,
    },
  });

  try {
    await client.send(
      new HeadBucketCommand({
        Bucket: options.bucket,
      }),
      {
        abortSignal: controller.signal,
      }
    );

    return {
      ok: true,
      message: `Bucket "${options.bucket}" reachable`,
    };
  } catch (error) {
    return {
      ok: false,
      message: error instanceof Error ? error.message : String(error),
    };
  } finally {
    clearTimeout(timeout);
    client.destroy();
  }
}

async function testR2Storage(values: Map<string, string>): Promise<StorageTestResult> {
  const accountId = values.get('R2_ACCOUNT_ID')?.trim() ?? '';

  const bucket = values.get('R2_BUCKET')?.trim() ?? '';

  const accessKeyId = values.get('R2_ACCESS_KEY_ID')?.trim() ?? '';

  const secretAccessKey = values.get('R2_SECRET_ACCESS_KEY')?.trim() ?? '';

  if (!accountId || !bucket || !accessKeyId || !secretAccessKey) {
    return {
      ok: false,
      message: 'R2 configuration is incomplete',
    };
  }

  return testS3Connection({
    endpoint: r2Endpoint(accountId),
    region: 'auto',
    bucket,
    accessKeyId,
    secretAccessKey,
  });
}

async function testGenericS3Storage(values: Map<string, string>): Promise<StorageTestResult> {
  const endpoint = normalizeEndpoint(values.get('S3_ENDPOINT') ?? '');

  const region = values.get('S3_REGION')?.trim() || 'us-east-1';

  const bucket = values.get('S3_BUCKET')?.trim() ?? '';

  const accessKeyId = values.get('S3_ACCESS_KEY_ID')?.trim() ?? '';

  const secretAccessKey = values.get('S3_SECRET_ACCESS_KEY')?.trim() ?? '';

  if (!bucket || !accessKeyId || !secretAccessKey) {
    return {
      ok: false,
      message: 'S3 configuration is incomplete',
    };
  }

  return testS3Connection({
    endpoint: endpoint || undefined,
    region,
    bucket,
    accessKeyId,
    secretAccessKey,
    forcePathStyle: values.get('S3_FORCE_PATH_STYLE') === 'true',
  });
}

async function testHuggingFaceStorage(values: Map<string, string>): Promise<StorageTestResult> {
  const endpoint = normalizeEndpoint(values.get('HF_URL') ?? '');

  const bucket = values.get('HF_BUCKET')?.trim() ?? '';

  const accessKeyId = values.get('HF_S3_ACCESS_KEY_ID')?.trim() ?? '';

  const secretAccessKey = values.get('HF_S3_SECRET_ACCESS_KEY')?.trim() ?? '';

  if (!endpoint) {
    return {
      ok: false,
      message: 'HF_URL / S3 endpoint is required for connection test',
    };
  }

  if (!bucket || !accessKeyId || !secretAccessKey) {
    return {
      ok: false,
      message: 'Hugging Face S3 configuration is incomplete',
    };
  }

  return testS3Connection({
    endpoint,
    region: 'us-east-1',
    bucket,
    accessKeyId,
    secretAccessKey,
    forcePathStyle: true,
  });
}

async function testLocalStorage(values: Map<string, string>): Promise<StorageTestResult> {
  const storagePath =
    values.get('MEMORY_LOCAL_STORAGE_PATH')?.trim() ||
    path.join(os.homedir(), '.local', 'share', 'toolnet-memory');

  const probe = path.join(storagePath, `.toolnet-test-${process.pid}-${Date.now()}`);

  try {
    fs.mkdirSync(storagePath, {
      recursive: true,
      mode: 0o700,
    });

    fs.writeFileSync(probe, 'toolnet-memory\n', {
      encoding: 'utf8',
      mode: 0o600,
    });

    fs.unlinkSync(probe);

    return {
      ok: true,
      message: `Writable: ${storagePath}`,
    };
  } catch (error) {
    return {
      ok: false,
      message: error instanceof Error ? error.message : String(error),
    };
  }
}

async function testStorage(
  provider: StorageProviderName,
  values: Map<string, string>
): Promise<StorageTestResult> {
  switch (provider) {
    case 'r2':
      return testR2Storage(values);

    case 's3':
      return testGenericS3Storage(values);

    case 'huggingface':
      return testHuggingFaceStorage(values);

    case 'local':
      return testLocalStorage(values);
  }
}

async function showStorageTest(
  provider: StorageProviderName,
  values: Map<string, string>
): Promise<StorageTestResult> {
  console.log('');
  console.log(`Testing ${providerLabel(provider)}...`);

  const result = await testStorage(provider, values);

  if (result.ok) {
    console.log(`✓ ${result.message}`);
  } else {
    console.log('✗ Connection test failed');
    console.log(`  ${result.message}`);
  }

  console.log('');

  return result;
}

function printHeader(): void {
  console.log('');
  console.log('╔══════════════════════════════════════╗');
  console.log('║         TOOLNET MEMORY SETUP         ║');
  console.log('╚══════════════════════════════════════╝');
  console.log('');
}

function printCurrentStatus(values: Map<string, string>): void {
  const provider = providerFrom(values);

  console.log('Current configuration');
  console.log('──────────────────────────────────────');
  console.log(
    `Storage : ${providerLabel(provider)} ${storageConfigured(values) ? '✓' : '⚠ incomplete'}`
  );

  const llmProvider = values.get('TOOLNET_LLM_PROVIDER');

  const llmModel = values.get('TOOLNET_LLM_MODEL');

  const embeddingProvider = values.get('TOOLNET_EMBEDDING_PROVIDER');

  console.log(
    `LLM     : ${
      llmProvider
        ? `${aiProviderLabel(llmProvider)}${llmModel ? ` / ${llmModel}` : ''}`
        : 'not configured'
    }`
  );

  console.log(`Embedding: ${embeddingProvider || 'legacy/default'}`);
  console.log('');
}

async function mainMenu(rl: readline.Interface): Promise<MainMenuChoice> {
  console.log('Setup');
  console.log('──────────────────────────────────────');
  console.log('  1. Storage');
  console.log('  2. AI Model');
  console.log('  3. Finish & Save');
  console.log('  0. Exit without saving');
  console.log('');

  const answer = (await rl.question('Choose [1-3]: ')).trim();

  if (answer === '1') {
    return 'storage';
  }

  if (answer === '2') {
    return 'ai';
  }

  if (answer === '0') {
    return 'exit';
  }

  if (answer === '3') {
    return 'finish';
  }

  return 'finish';
}

async function chooseStorageProvider(
  rl: readline.Interface,
  current: StorageProviderName
): Promise<StorageProviderName | 'back'> {
  console.log('');
  console.log('Storage');
  console.log('──────────────────────────────────────');
  console.log(`  1. Cloudflare R2${current === 'r2' ? '  ✓ current' : ''}`);
  console.log(`  2. S3 / S3-compatible${current === 's3' ? '  ✓ current' : ''}`);
  console.log(`  3. Hugging Face S3${current === 'huggingface' ? '  ✓ current' : ''}`);
  console.log(`  4. Local${current === 'local' ? '  ✓ current' : ''}`);
  console.log('');
  console.log('  0. Back');
  console.log('');

  const answer = (await rl.question('Choose storage: ')).trim();

  if (answer === '0') {
    return 'back';
  }

  if (answer === '2') {
    return 's3';
  }

  if (answer === '3') {
    return 'huggingface';
  }

  if (answer === '4') {
    return 'local';
  }

  return 'r2';
}

async function configureR2(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  console.log('');
  console.log('Cloudflare R2');
  console.log('──────────────────────────────────────');

  const accountId = await rl.question(
    values.get('R2_ACCOUNT_ID') ? `ACCOUNT ID [${values.get('R2_ACCOUNT_ID')}]: ` : 'ACCOUNT ID: '
  );

  const access = await rl.question(
    values.get('R2_ACCESS_KEY_ID')
      ? `ACCESS KEY ID [${masked(values.get('R2_ACCESS_KEY_ID'))}]: `
      : 'ACCESS KEY ID: '
  );

  const bucket = await rl.question(`BUCKET [${values.get('R2_BUCKET') || 'toolnet-memory'}]: `);

  setIfEntered(values, 'R2_ACCOUNT_ID', accountId);

  setIfEntered(values, 'R2_ACCESS_KEY_ID', access);

  setIfEntered(values, 'R2_BUCKET', bucket, 'toolnet-memory');

  const finalAccountId = values.get('R2_ACCOUNT_ID')?.trim();

  if (finalAccountId) {
    console.log(`URL: ${r2Endpoint(finalAccountId)}`);
  }

  const secret = await secretQuestion(
    rl,
    values.get('R2_SECRET_ACCESS_KEY')
      ? 'SECRET ACCESS KEY [configured, Enter = keep]: '
      : 'SECRET ACCESS KEY: '
  );

  if (secret.trim()) {
    values.set('R2_SECRET_ACCESS_KEY', secret.trim());
  }
}

async function configureS3(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  console.log('');
  console.log('S3 / S3-compatible');
  console.log('──────────────────────────────────────');

  const endpoint = await rl.question(
    values.get('S3_ENDPOINT')
      ? `URL / ENDPOINT [${values.get('S3_ENDPOINT')}]: `
      : 'URL / ENDPOINT [blank = AWS S3]: '
  );

  const region = await rl.question(`REGION [${values.get('S3_REGION') || 'us-east-1'}]: `);

  const access = await rl.question(
    values.get('S3_ACCESS_KEY_ID')
      ? `ACCESS KEY ID [${masked(values.get('S3_ACCESS_KEY_ID'))}]: `
      : 'ACCESS KEY ID: '
  );

  const bucket = await rl.question(`BUCKET [${values.get('S3_BUCKET') || 'toolnet-memory'}]: `);

  const currentPathStyle = values.get('S3_FORCE_PATH_STYLE') === 'true';

  const pathStyle = await rl.question(`FORCE PATH STYLE [${currentPathStyle ? 'Y' : 'N'}] (y/n): `);

  if (endpoint.trim()) {
    values.set('S3_ENDPOINT', normalizeEndpoint(endpoint));
  }

  setIfEntered(values, 'S3_REGION', region, 'us-east-1');

  setIfEntered(values, 'S3_ACCESS_KEY_ID', access);

  setIfEntered(values, 'S3_BUCKET', bucket, 'toolnet-memory');

  if (pathStyle.trim()) {
    const value = pathStyle.trim().toLowerCase();

    values.set('S3_FORCE_PATH_STYLE', value === 'y' || value === 'yes' ? 'true' : 'false');
  } else if (!values.has('S3_FORCE_PATH_STYLE')) {
    values.set('S3_FORCE_PATH_STYLE', 'false');
  }

  const secret = await secretQuestion(
    rl,
    values.get('S3_SECRET_ACCESS_KEY')
      ? 'SECRET ACCESS KEY [configured, Enter = keep]: '
      : 'SECRET ACCESS KEY: '
  );

  if (secret.trim()) {
    values.set('S3_SECRET_ACCESS_KEY', secret.trim());
  }
}

async function configureHuggingFace(
  rl: readline.Interface,
  values: Map<string, string>
): Promise<void> {
  console.log('');
  console.log('Hugging Face S3');
  console.log('──────────────────────────────────────');

  const namespace = await rl.question(
    values.get('HF_NAMESPACE')
      ? `NAMESPACE [${values.get('HF_NAMESPACE')}]: `
      : 'NAMESPACE [optional]: '
  );

  const access = await rl.question(
    values.get('HF_S3_ACCESS_KEY_ID')
      ? `ACCESS KEY ID [${masked(values.get('HF_S3_ACCESS_KEY_ID'))}]: `
      : 'ACCESS KEY ID: '
  );

  const bucket = await rl.question(`BUCKET [${values.get('HF_BUCKET') || 'toolnet-memory'}]: `);

  const url = await rl.question(
    values.get('HF_URL') ? `URL [${values.get('HF_URL')}]: ` : 'URL / S3 ENDPOINT: '
  );

  setIfEntered(values, 'HF_NAMESPACE', namespace);

  setIfEntered(values, 'HF_S3_ACCESS_KEY_ID', access);

  setIfEntered(values, 'HF_BUCKET', bucket, 'toolnet-memory');

  if (url.trim()) {
    values.set('HF_URL', normalizeEndpoint(url));
  }

  const secret = await secretQuestion(
    rl,
    values.get('HF_S3_SECRET_ACCESS_KEY')
      ? 'SECRET ACCESS KEY [configured, Enter = keep]: '
      : 'SECRET ACCESS KEY: '
  );

  if (secret.trim()) {
    values.set('HF_S3_SECRET_ACCESS_KEY', secret.trim());
  }
}

async function configureLocal(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  console.log('');
  console.log('Local Storage');
  console.log('──────────────────────────────────────');

  const defaultPath =
    values.get('MEMORY_LOCAL_STORAGE_PATH') ??
    path.join(os.homedir(), '.local', 'share', 'toolnet-memory');

  const storagePath = await rl.question(`LOCAL PATH [${defaultPath}]: `);

  setIfEntered(values, 'MEMORY_LOCAL_STORAGE_PATH', storagePath, defaultPath);
}

async function storageWizard(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  const original = new Map(values);

  while (true) {
    const provider = await chooseStorageProvider(rl, providerFrom(values));

    if (provider === 'back') {
      return;
    }

    const providerSnapshot = new Map(values);

    values.set('MEMORY_STORAGE_PROVIDER', provider);

    if (provider === 'r2') {
      await configureR2(rl, values);
    } else if (provider === 's3') {
      await configureS3(rl, values);
    } else if (provider === 'huggingface') {
      await configureHuggingFace(rl, values);
    } else {
      await configureLocal(rl, values);
    }

    const missing = requiredFor(provider).filter((key) => !values.get(key)?.trim());

    if (missing.length) {
      console.log('');
      console.log('⚠ Missing required fields:');

      for (const key of missing) {
        console.log(`  - ${key}`);
      }

      console.log('');
      console.log('  1. Retry');
      console.log('  2. Save anyway');
      console.log('  3. Choose another provider');
      console.log('  4. Cancel');
      console.log('');

      const action = (await rl.question('Choose [1]: ')).trim() || '1';

      if (action === '2') {
        saveEnv(values);

        console.log('');
        console.log('⚠ Saved with incomplete configuration');
        console.log('');
        return;
      }

      if (action === '3') {
        values.clear();

        for (const [key, value] of providerSnapshot) {
          values.set(key, value);
        }

        continue;
      }

      if (action === '4') {
        values.clear();

        for (const [key, value] of original) {
          values.set(key, value);
        }

        console.log('');
        console.log('Storage changes cancelled.');
        console.log('');
        return;
      }

      continue;
    }

    const result = await showStorageTest(provider, values);

    if (result.ok) {
      saveEnv(values);

      console.log(`✓ ${providerLabel(provider)} configuration saved`);
      console.log(`  ${ENV_FILE}`);
      console.log('');

      return;
    }

    console.log('  1. Retry');
    console.log('  2. Save anyway');
    console.log('  3. Choose another provider');
    console.log('  4. Cancel');
    console.log('');

    const action = (await rl.question('Choose [1]: ')).trim() || '1';

    if (action === '2') {
      saveEnv(values);

      console.log('');
      console.log('⚠ Saved even though connection test failed');
      console.log('');

      return;
    }

    if (action === '3') {
      values.clear();

      for (const [key, value] of providerSnapshot) {
        values.set(key, value);
      }

      continue;
    }

    if (action === '4') {
      values.clear();

      for (const [key, value] of original) {
        values.set(key, value);
      }

      console.log('');
      console.log('Storage changes cancelled.');
      console.log('');

      return;
    }
  }
}

type AiWizardDefinition = {
  id: AiProviderId;
  label: string;
  baseUrl?: string;
  suggestedModel?: string;
  apiKeyRequired: boolean;
  accountIdRequired?: boolean;
  baseUrlRequired?: boolean;
};

const AI_WIZARD_PROVIDERS: readonly AiWizardDefinition[] = [
  {
    id: 'openai-compatible',
    label: 'OpenAI-compatible',
    apiKeyRequired: true,
    baseUrlRequired: true,
  },

  {
    id: 'alibaba',
    label: 'Alibaba / DashScope',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    suggestedModel: 'qwen3.6-flash',
    apiKeyRequired: true,
  },

  {
    id: 'openrouter',
    label: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyRequired: true,
  },

  {
    id: 'groq',
    label: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    apiKeyRequired: true,
  },

  {
    id: 'deepseek',
    label: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    suggestedModel: 'deepseek-v4-flash',
    apiKeyRequired: true,
  },

  {
    id: 'nvidia',
    label: 'NVIDIA NIM',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    suggestedModel: 'deepseek-ai/deepseek-v4-pro',
    apiKeyRequired: true,
  },

  {
    id: 'gemini',
    label: 'Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    suggestedModel: 'gemini-3.6-flash',
    apiKeyRequired: true,
  },

  {
    id: 'huggingface',
    label: 'Hugging Face',
    baseUrl: 'https://router.huggingface.co/v1',
    apiKeyRequired: true,
  },

  {
    id: 'ollama',
    label: 'Ollama / Local',
    baseUrl: 'http://127.0.0.1:11434/v1',
    apiKeyRequired: false,
  },

  {
    id: 'custom',
    label: 'Custom endpoint',
    apiKeyRequired: false,
    baseUrlRequired: true,
  },

  {
    id: 'cloudflare',
    label: 'Cloudflare Workers AI',
    suggestedModel: '@cf/meta/llama-3.1-8b-instruct',
    apiKeyRequired: true,
    accountIdRequired: true,
  },
] as const;

function aiProviderDefinition(id: string | undefined): AiWizardDefinition | undefined {
  return AI_WIZARD_PROVIDERS.find((provider) => provider.id === id);
}

function aiProviderLabel(id: string | undefined): string {
  return aiProviderDefinition(id)?.label ?? id ?? 'not configured';
}

function currentAiProvider(values: Map<string, string>): AiProviderId | undefined {
  const provider = values.get('TOOLNET_LLM_PROVIDER')?.trim();

  return AI_WIZARD_PROVIDERS.some((item) => item.id === provider)
    ? (provider as AiProviderId)
    : undefined;
}

async function chooseAiProvider(
  rl: readline.Interface,
  current?: AiProviderId
): Promise<AiProviderId | 'back'> {
  console.log('');
  console.log('AI Model');
  console.log('──────────────────────────────────────');

  AI_WIZARD_PROVIDERS.forEach((provider, index) => {
    console.log(`  ${index + 1}. ${provider.label}${current === provider.id ? '  ✓ current' : ''}`);
  });

  console.log('');
  console.log('  0. Back');
  console.log('');

  const answer = (await rl.question('Choose provider: ')).trim();

  if (answer === '0') {
    return 'back';
  }

  const index = Number(answer) - 1;

  if (Number.isInteger(index) && index >= 0 && index < AI_WIZARD_PROVIDERS.length) {
    return AI_WIZARD_PROVIDERS[index].id;
  }

  console.log('');
  console.log('⚠ Invalid provider selection');

  return chooseAiProvider(rl, current);
}

function aiConfigComplete(values: Map<string, string>, definition: AiWizardDefinition): boolean {
  const model = values.get('TOOLNET_LLM_MODEL')?.trim();

  if (!model) {
    return false;
  }

  if (definition.apiKeyRequired && !values.get('TOOLNET_LLM_API_KEY')?.trim()) {
    return false;
  }

  if (definition.accountIdRequired && !values.get('TOOLNET_LLM_ACCOUNT_ID')?.trim()) {
    return false;
  }

  if (definition.baseUrlRequired && !values.get('TOOLNET_LLM_BASE_URL')?.trim()) {
    return false;
  }

  return true;
}

function clearCanonicalLlm(values: Map<string, string>): void {
  values.delete('TOOLNET_LLM_API_KEY');

  values.delete('TOOLNET_LLM_BASE_URL');

  values.delete('TOOLNET_LLM_MODEL');

  values.delete('TOOLNET_LLM_ACCOUNT_ID');
}

async function configureAiProvider(
  rl: readline.Interface,
  values: Map<string, string>,
  definition: AiWizardDefinition
): Promise<void> {
  console.log('');
  console.log(definition.label);
  console.log('──────────────────────────────────────');

  const existingProvider = values.get('TOOLNET_LLM_PROVIDER');

  /*
   * Changing provider must not
   * accidentally reuse another
   * provider's endpoint/key/model.
   */
  if (existingProvider && existingProvider !== definition.id) {
    clearCanonicalLlm(values);
  }

  values.set('TOOLNET_LLM_PROVIDER', definition.id);

  if (definition.accountIdRequired) {
    const current = values.get('TOOLNET_LLM_ACCOUNT_ID');

    const accountId = await rl.question(current ? `ACCOUNT ID [${current}]: ` : 'ACCOUNT ID: ');

    setIfEntered(values, 'TOOLNET_LLM_ACCOUNT_ID', accountId);
  } else {
    values.delete('TOOLNET_LLM_ACCOUNT_ID');
  }

  if (definition.apiKeyRequired || definition.id === 'custom') {
    const currentKey = values.get('TOOLNET_LLM_API_KEY');

    const apiKey = await secretQuestion(
      rl,
      currentKey
        ? 'API KEY [configured, Enter = keep]: '
        : definition.apiKeyRequired
          ? 'API KEY: '
          : 'API KEY [optional]: '
    );

    if (apiKey.trim()) {
      values.set('TOOLNET_LLM_API_KEY', apiKey.trim());
    }
  } else {
    values.delete('TOOLNET_LLM_API_KEY');
  }

  if (definition.id !== 'cloudflare') {
    const currentBase = values.get('TOOLNET_LLM_BASE_URL');

    const defaultBase = currentBase || definition.baseUrl || '';

    const baseUrl = await rl.question(
      defaultBase
        ? `BASE URL [${defaultBase}]: `
        : definition.baseUrlRequired
          ? 'BASE URL: '
          : 'BASE URL [optional]: '
    );

    const resolvedBase = baseUrl.trim() || defaultBase;

    if (resolvedBase) {
      values.set('TOOLNET_LLM_BASE_URL', normalizeEndpoint(resolvedBase));
    } else {
      values.delete('TOOLNET_LLM_BASE_URL');
    }
  } else {
    /*
     * Cloudflare provider builds
     * /accounts/{id}/ai/run itself.
     */
    values.delete('TOOLNET_LLM_BASE_URL');
  }

  const currentModel = values.get('TOOLNET_LLM_MODEL');

  const modelDefault = currentModel || definition.suggestedModel || '';

  const model = await rl.question(modelDefault ? `MODEL [${modelDefault}]: ` : 'MODEL: ');

  const resolvedModel = model.trim() || modelDefault;

  if (resolvedModel) {
    values.set('TOOLNET_LLM_MODEL', resolvedModel);
  }
}

function aiProviderConfigFromValues(values: Map<string, string>): AiProviderConfig {
  const provider = currentAiProvider(values);

  if (!provider) {
    throw new Error('AI provider is not configured');
  }

  return {
    id: provider,

    apiKey: values.get('TOOLNET_LLM_API_KEY')?.trim() || undefined,

    baseUrl: values.get('TOOLNET_LLM_BASE_URL')?.trim() || undefined,

    model: values.get('TOOLNET_LLM_MODEL')?.trim() || undefined,

    accountId: values.get('TOOLNET_LLM_ACCOUNT_ID')?.trim() || undefined,
  };
}

async function testAiProvider(values: Map<string, string>): Promise<{
  ok: boolean;
  message: string;
}> {
  const config = aiProviderConfigFromValues(values);

  console.log('');
  console.log(`Testing ${aiProviderLabel(config.id)}...`);

  try {
    const provider = createAiProvider(config);

    const result = await provider.healthCheck();

    if (result.ok) {
      console.log(`✓ Provider reachable${result.latencyMs ? ` (${result.latencyMs} ms)` : ''}`);

      console.log(`✓ Model: ${result.model ?? config.model ?? 'configured'}`);

      console.log('');

      return {
        ok: true,
        message: result.message,
      };
    }

    console.log('✗ AI provider test failed');

    console.log(`  ${result.message}`);

    console.log('');

    return {
      ok: false,
      message: result.message,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    console.log('✗ AI provider test failed');

    console.log(`  ${message}`);

    console.log('');

    return {
      ok: false,
      message,
    };
  }
}

type EmbeddingWizardProvider = {
  id: AiProviderId | 'local';
  label: string;
  baseUrl?: string;
  suggestedModel?: string;
  apiKeyRequired: boolean;
  accountIdRequired?: boolean;
  baseUrlRequired?: boolean;
};

const EMBEDDING_WIZARD_PROVIDERS: readonly EmbeddingWizardProvider[] = [
  {
    id: 'local',
    label: 'Local / Hash',
    apiKeyRequired: false,
  },

  {
    id: 'huggingface',
    label: 'Hugging Face',
    suggestedModel: 'sentence-transformers/all-MiniLM-L6-v2',
    apiKeyRequired: true,
  },

  {
    id: 'openai-compatible',
    label: 'OpenAI-compatible',
    apiKeyRequired: true,
    baseUrlRequired: true,
  },

  {
    id: 'alibaba',
    label: 'Alibaba / DashScope',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    suggestedModel: 'text-embedding-v4',
    apiKeyRequired: true,
  },

  {
    id: 'openrouter',
    label: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyRequired: true,
  },

  {
    id: 'nvidia',
    label: 'NVIDIA NIM',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    apiKeyRequired: true,
  },

  {
    id: 'ollama',
    label: 'Ollama / Local',
    baseUrl: 'http://127.0.0.1:11434/v1',
    apiKeyRequired: false,
  },

  {
    id: 'gemini',
    label: 'Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    suggestedModel: 'gemini-embedding-001',
    apiKeyRequired: true,
  },

  {
    id: 'cloudflare',
    label: 'Cloudflare Workers AI',
    suggestedModel: '@cf/baai/bge-base-en-v1.5',
    apiKeyRequired: true,
    accountIdRequired: true,
  },

  {
    id: 'custom',
    label: 'Custom OpenAI-compatible endpoint',
    apiKeyRequired: false,
    baseUrlRequired: true,
  },
] as const;

function embeddingProviderLabel(id: string | undefined): string {
  return EMBEDDING_WIZARD_PROVIDERS.find((item) => item.id === id)?.label ?? id ?? 'not configured';
}

async function chooseEmbeddingProvider(
  rl: readline.Interface,
  current?: string
): Promise<EmbeddingWizardProvider | 'back'> {
  console.log('');
  console.log('Embedding Model');
  console.log('──────────────────────────────────────');

  EMBEDDING_WIZARD_PROVIDERS.forEach((provider, index) => {
    console.log(`  ${index + 1}. ${provider.label}${current === provider.id ? '  ✓ current' : ''}`);
  });

  console.log('');
  console.log('  0. Back');
  console.log('');

  const answer = (await rl.question('Choose embedding provider: ')).trim();

  if (answer === '0') {
    return 'back';
  }

  const index = Number(answer) - 1;

  if (Number.isInteger(index) && index >= 0 && index < EMBEDDING_WIZARD_PROVIDERS.length) {
    return EMBEDDING_WIZARD_PROVIDERS[index];
  }

  console.log('');
  console.log('⚠ Invalid selection');

  return chooseEmbeddingProvider(rl, current);
}

function clearEmbeddingConfig(values: Map<string, string>): void {
  values.delete('TOOLNET_EMBEDDING_API_KEY');

  values.delete('TOOLNET_EMBEDDING_BASE_URL');

  values.delete('TOOLNET_EMBEDDING_MODEL');

  values.delete('TOOLNET_EMBEDDING_ACCOUNT_ID');
}

async function configureEmbedding(
  rl: readline.Interface,
  values: Map<string, string>,
  definition: EmbeddingWizardProvider
): Promise<void> {
  const previous = values.get('TOOLNET_EMBEDDING_PROVIDER');

  if (previous && previous !== definition.id) {
    clearEmbeddingConfig(values);
  }

  values.set('TOOLNET_EMBEDDING_PROVIDER', definition.id);

  console.log('');
  console.log(definition.label);
  console.log('──────────────────────────────────────');

  if (definition.id === 'local') {
    clearEmbeddingConfig(values);

    console.log('✓ Local embedding selected');

    console.log('  No API key required.');

    return;
  }

  if (definition.accountIdRequired) {
    const current = values.get('TOOLNET_EMBEDDING_ACCOUNT_ID');

    const accountId = await rl.question(current ? `ACCOUNT ID [${current}]: ` : 'ACCOUNT ID: ');

    setIfEntered(values, 'TOOLNET_EMBEDDING_ACCOUNT_ID', accountId);
  } else {
    values.delete('TOOLNET_EMBEDDING_ACCOUNT_ID');
  }

  if (definition.apiKeyRequired || definition.id === 'custom') {
    const existing = values.get('TOOLNET_EMBEDDING_API_KEY');

    const key = await secretQuestion(
      rl,
      existing
        ? 'API KEY [configured, Enter = keep]: '
        : definition.apiKeyRequired
          ? 'API KEY: '
          : 'API KEY [optional]: '
    );

    if (key.trim()) {
      values.set('TOOLNET_EMBEDDING_API_KEY', key.trim());
    }
  } else {
    values.delete('TOOLNET_EMBEDDING_API_KEY');
  }

  if (definition.id === 'cloudflare') {
    const accountId = values.get('TOOLNET_EMBEDDING_ACCOUNT_ID')?.trim();

    if (accountId) {
      const url = `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/v1`;

      values.set('TOOLNET_EMBEDDING_BASE_URL', url);

      console.log(`BASE URL: ${url}`);
    }
  } else {
    const existing = values.get('TOOLNET_EMBEDDING_BASE_URL');

    const defaultBase = existing || definition.baseUrl || '';

    const entered = await rl.question(
      defaultBase
        ? `BASE URL [${defaultBase}]: `
        : definition.baseUrlRequired
          ? 'BASE URL: '
          : 'BASE URL [optional]: '
    );

    const resolved = entered.trim() || defaultBase;

    if (resolved) {
      values.set('TOOLNET_EMBEDDING_BASE_URL', normalizeEndpoint(resolved));
    }
  }

  const currentModel = values.get('TOOLNET_EMBEDDING_MODEL');

  const defaultModel = currentModel || definition.suggestedModel || '';

  const model = await rl.question(defaultModel ? `MODEL [${defaultModel}]: ` : 'MODEL: ');

  const resolvedModel = model.trim() || defaultModel;

  if (resolvedModel) {
    values.set('TOOLNET_EMBEDDING_MODEL', resolvedModel);
  }
}

function embeddingConfigComplete(
  values: Map<string, string>,
  definition: EmbeddingWizardProvider
): boolean {
  if (definition.id === 'local') {
    return true;
  }

  if (definition.apiKeyRequired && !values.get('TOOLNET_EMBEDDING_API_KEY')?.trim()) {
    return false;
  }

  if (definition.accountIdRequired && !values.get('TOOLNET_EMBEDDING_ACCOUNT_ID')?.trim()) {
    return false;
  }

  if (definition.baseUrlRequired && !values.get('TOOLNET_EMBEDDING_BASE_URL')?.trim()) {
    return false;
  }

  return Boolean(values.get('TOOLNET_EMBEDDING_MODEL')?.trim());
}

async function testEmbeddingConfig(values: Map<string, string>): Promise<boolean> {
  const provider = values.get('TOOLNET_EMBEDDING_PROVIDER')?.trim();

  console.log('');
  console.log(`Testing embedding: ${embeddingProviderLabel(provider)}...`);

  if (provider === 'local') {
    console.log('✓ Local embedding ready');

    console.log('');
    return true;
  }

  const apiKey = values.get('TOOLNET_EMBEDDING_API_KEY')?.trim();

  const model = values.get('TOOLNET_EMBEDDING_MODEL')?.trim();

  let baseUrl = values.get('TOOLNET_EMBEDDING_BASE_URL')?.trim();

  try {
    if (!model) {
      throw new Error('Embedding model is missing');
    }

    if (provider === 'huggingface') {
      if (!apiKey) {
        throw new Error('API key is missing');
      }

      const response = await fetch(
        `https://router.huggingface.co/hf-inference/models/${model}/pipeline/feature-extraction`,
        {
          method: 'POST',

          headers: {
            Authorization: `Bearer ${apiKey}`,

            'Content-Type': 'application/json',
          },

          body: JSON.stringify({
            inputs: ['toolnet memory test'],
          }),
        }
      );

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${await response.text()}`);
      }
    } else if (provider === 'gemini') {
      if (!apiKey) {
        throw new Error('API key is missing');
      }

      const normalizedModel = model.replace(/^models\//, '');

      baseUrl = baseUrl || 'https://generativelanguage.googleapis.com/v1beta';

      const response = await fetch(
        `${baseUrl.replace(/\/+$/, '')}/models/${encodeURIComponent(
          normalizedModel
        )}:embedContent?key=${encodeURIComponent(apiKey)}`,
        {
          method: 'POST',

          headers: {
            'content-type': 'application/json',
          },

          body: JSON.stringify({
            model: `models/${normalizedModel}`,

            content: {
              parts: [
                {
                  text: 'toolnet memory test',
                },
              ],
            },
          }),
        }
      );

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${await response.text()}`);
      }
    } else {
      if (!baseUrl) {
        throw new Error('BASE URL is missing');
      }

      const response = await fetch(`${baseUrl.replace(/\/+$/, '')}/embeddings`, {
        method: 'POST',

        headers: {
          'content-type': 'application/json',

          ...(apiKey
            ? {
                authorization: `Bearer ${apiKey}`,
              }
            : {}),
        },

        body: JSON.stringify({
          model,

          input: ['toolnet memory test'],
        }),
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${await response.text()}`);
      }

      const body = (await response.json()) as {
        data?: Array<{
          embedding?: number[];
        }>;
      };

      if (!Array.isArray(body.data) || !Array.isArray(body.data[0]?.embedding)) {
        throw new Error('Invalid embedding response');
      }
    }

    console.log('✓ Embedding provider reachable');

    console.log(`✓ Model: ${model}`);

    console.log('');
    return true;
  } catch (error) {
    console.log('✗ Embedding test failed');

    console.log(`  ${error instanceof Error ? error.message : String(error)}`);

    console.log('');
    return false;
  }
}

async function embeddingWizard(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  const original = new Map(values);

  while (true) {
    const definition = await chooseEmbeddingProvider(rl, values.get('TOOLNET_EMBEDDING_PROVIDER'));

    if (definition === 'back') {
      return;
    }

    await configureEmbedding(rl, values, definition);

    if (!embeddingConfigComplete(values, definition)) {
      console.log('');
      console.log('⚠ Embedding configuration is incomplete.');

      console.log('');
      console.log('  1. Retry');
      console.log('  2. Save anyway');
      console.log('  3. Choose another provider');
      console.log('  4. Cancel');
      console.log('');

      const action = (await rl.question('Choose [1]: ')).trim() || '1';

      if (action === '2') {
        saveEnv(values);
        return;
      }

      if (action === '3') {
        continue;
      }

      if (action === '4') {
        values.clear();

        for (const [key, value] of original) {
          values.set(key, value);
        }

        return;
      }

      continue;
    }

    const ok = await testEmbeddingConfig(values);

    if (ok) {
      saveEnv(values);

      console.log(`✓ ${definition.label} embedding configuration saved`);

      console.log(`  ${ENV_FILE}`);

      console.log('');
      return;
    }

    console.log('  1. Retry');

    console.log('  2. Save anyway');

    console.log('  3. Choose another provider');

    console.log('  4. Cancel');

    console.log('');

    const action = (await rl.question('Choose [1]: ')).trim() || '1';

    if (action === '2') {
      saveEnv(values);
      return;
    }

    if (action === '3') {
      continue;
    }

    if (action === '4') {
      values.clear();

      for (const [key, value] of original) {
        values.set(key, value);
      }

      return;
    }
  }
}

async function copyLlmToEmbedding(
  rl: readline.Interface,
  values: Map<string, string>
): Promise<void> {
  const provider = values.get('TOOLNET_LLM_PROVIDER')?.trim();

  if (!provider) {
    console.log('');
    console.log('⚠ Configure LLM first.');
    console.log('');
    return;
  }

  /*
   * DeepSeek and Groq currently remain
   * LLM-only in ToolNet's embedding wizard.
   */
  if (provider === 'deepseek' || provider === 'groq') {
    console.log('');
    console.log(`⚠ ${aiProviderLabel(provider)} is configured as LLM-only.`);

    console.log('Choose Embedding separately.');

    console.log('');
    return;
  }

  values.set('TOOLNET_EMBEDDING_PROVIDER', provider);

  const key = values.get('TOOLNET_LLM_API_KEY');

  const baseUrl = values.get('TOOLNET_LLM_BASE_URL');

  const accountId = values.get('TOOLNET_LLM_ACCOUNT_ID');

  if (key) {
    values.set('TOOLNET_EMBEDDING_API_KEY', key);
  }

  if (baseUrl) {
    values.set('TOOLNET_EMBEDDING_BASE_URL', baseUrl);
  }

  if (accountId) {
    values.set('TOOLNET_EMBEDDING_ACCOUNT_ID', accountId);
  }

  let suggested = '';

  if (provider === 'alibaba') {
    suggested = 'text-embedding-v4';
  } else if (provider === 'gemini') {
    suggested = 'gemini-embedding-001';
  } else if (provider === 'cloudflare') {
    suggested = '@cf/baai/bge-base-en-v1.5';
  } else if (provider === 'huggingface') {
    suggested = 'sentence-transformers/all-MiniLM-L6-v2';
  }

  const model = await rl.question(
    suggested ? `EMBEDDING MODEL [${suggested}]: ` : 'EMBEDDING MODEL: '
  );

  const resolved = model.trim() || suggested;

  if (!resolved) {
    console.log('');
    console.log('⚠ Embedding model is required.');
    console.log('');
    return;
  }

  values.set('TOOLNET_EMBEDDING_MODEL', resolved);

  const ok = await testEmbeddingConfig(values);

  if (!ok) {
    const save = (await rl.question('Save anyway? (y/N): ')).trim().toLowerCase();

    if (save !== 'y' && save !== 'yes') {
      return;
    }
  }

  saveEnv(values);

  console.log('');
  console.log('✓ LLM credentials reused for Embedding');

  console.log(`✓ Embedding model: ${resolved}`);

  console.log('');
}

function fallbackPrefix(slot: 1 | 2): string {
  return `TOOLNET_LLM_FALLBACK_${slot}`;
}

function clearFallback(values: Map<string, string>, slot: 1 | 2): void {
  const prefix = fallbackPrefix(slot);

  for (const suffix of ['PROVIDER', 'API_KEY', 'BASE_URL', 'MODEL', 'ACCOUNT_ID']) {
    values.delete(`${prefix}_${suffix}`);
  }
}

function fallbackProviderName(values: Map<string, string>, slot: 1 | 2): string {
  const prefix = fallbackPrefix(slot);

  const provider = values.get(`${prefix}_PROVIDER`);

  if (!provider) {
    return 'not configured';
  }

  const model = values.get(`${prefix}_MODEL`);

  return `${aiProviderLabel(provider)}${model ? ` / ${model}` : ''}`;
}

async function configureFallbackSlot(
  rl: readline.Interface,
  values: Map<string, string>,
  slot: 1 | 2
): Promise<void> {
  console.log('');
  console.log(`Fallback ${slot}`);

  console.log('──────────────────────────────────────');

  const selected = await chooseAiProvider(rl, undefined);

  if (selected === 'back') {
    return;
  }

  const primary = values.get('TOOLNET_LLM_PROVIDER');

  if (selected === primary) {
    console.log('');
    console.log('⚠ Fallback cannot be the same provider as Primary.');
    console.log('');
    return;
  }

  const otherSlot: 1 | 2 = slot === 1 ? 2 : 1;

  const otherProvider = values.get(`${fallbackPrefix(otherSlot)}_PROVIDER`);

  if (selected === otherProvider) {
    console.log('');
    console.log('⚠ This provider is already used by the other fallback.');
    console.log('');
    return;
  }

  const definition = AI_WIZARD_PROVIDERS.find((item) => item.id === selected);

  if (!definition) {
    return;
  }

  const prefix = fallbackPrefix(slot);

  clearFallback(values, slot);

  values.set(`${prefix}_PROVIDER`, selected);

  if (definition.accountIdRequired) {
    const accountId = await rl.question('ACCOUNT ID: ');

    if (accountId.trim()) {
      values.set(`${prefix}_ACCOUNT_ID`, accountId.trim());
    }
  }

  if (definition.apiKeyRequired || selected === 'custom') {
    const apiKey = await secretQuestion(
      rl,
      definition.apiKeyRequired ? 'API KEY: ' : 'API KEY [optional]: '
    );

    if (apiKey.trim()) {
      values.set(`${prefix}_API_KEY`, apiKey.trim());
    }
  }

  if (selected === 'cloudflare') {
    const accountId = values.get(`${prefix}_ACCOUNT_ID`);

    if (accountId) {
      values.set(
        `${prefix}_BASE_URL`,
        `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai`
      );
    }
  } else {
    const defaultBase = definition.baseUrl ?? '';

    const baseUrl = await rl.question(
      defaultBase
        ? `BASE URL [${defaultBase}]: `
        : definition.baseUrlRequired
          ? 'BASE URL: '
          : 'BASE URL [optional]: '
    );

    const resolved = baseUrl.trim() || defaultBase;

    if (resolved) {
      values.set(`${prefix}_BASE_URL`, normalizeEndpoint(resolved));
    }
  }

  const defaultModel = definition.suggestedModel ?? '';

  const model = await rl.question(defaultModel ? `MODEL [${defaultModel}]: ` : 'MODEL: ');

  const resolvedModel = model.trim() || defaultModel;

  if (!resolvedModel) {
    console.log('');
    console.log('⚠ MODEL is required.');
    console.log('');

    clearFallback(values, slot);

    return;
  }

  values.set(`${prefix}_MODEL`, resolvedModel);

  saveEnv(values);

  console.log('');
  console.log(`✓ Fallback ${slot} saved`);

  console.log(`  ${aiProviderLabel(selected)} / ${resolvedModel}`);

  console.log('');
}

async function fallbackPolicyWizard(
  rl: readline.Interface,
  values: Map<string, string>
): Promise<void> {
  const currentCooldown = values.get('TOOLNET_LLM_FALLBACK_COOLDOWN_MS') || '60000';

  const currentRetries = values.get('TOOLNET_LLM_MAX_RETRIES') || '1';

  console.log('');
  console.log('Fallback Policy');

  console.log('──────────────────────────────────────');

  const cooldownInput = await rl.question(`COOLDOWN MS [${currentCooldown}]: `);

  if (cooldownInput.trim()) {
    const cooldown = Number(cooldownInput.trim());

    if (Number.isFinite(cooldown) && cooldown >= 0) {
      values.set('TOOLNET_LLM_FALLBACK_COOLDOWN_MS', String(Math.floor(cooldown)));
    } else {
      console.log('⚠ Invalid cooldown; keeping previous value.');
    }
  }

  const retriesInput = await rl.question(`MAX RETRIES [${currentRetries}]: `);

  if (retriesInput.trim()) {
    const retries = Number(retriesInput.trim());

    if (Number.isFinite(retries) && retries >= 0 && retries <= 5) {
      values.set('TOOLNET_LLM_MAX_RETRIES', String(Math.floor(retries)));
    } else {
      console.log('⚠ MAX RETRIES must be between 0 and 5.');
    }
  }

  saveEnv(values);

  console.log('');
  console.log('✓ Fallback policy saved');

  console.log('');
}

async function fallbackWizard(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  while (true) {
    console.log('');
    console.log('LLM Fallback');

    console.log('──────────────────────────────────────');

    console.log(
      `  Primary    : ${
        values.get('TOOLNET_LLM_PROVIDER')
          ? `${aiProviderLabel(values.get('TOOLNET_LLM_PROVIDER'))} / ${
              values.get('TOOLNET_LLM_MODEL') || 'model not configured'
            }`
          : 'not configured'
      }`
    );

    console.log(`  Fallback 1 : ${fallbackProviderName(values, 1)}`);

    console.log(`  Fallback 2 : ${fallbackProviderName(values, 2)}`);

    console.log(`  Cooldown   : ${values.get('TOOLNET_LLM_FALLBACK_COOLDOWN_MS') || '60000'} ms`);

    console.log(`  Retries    : ${values.get('TOOLNET_LLM_MAX_RETRIES') || '1'}`);

    console.log('');
    console.log('  1. Configure Fallback 1');

    console.log('  2. Configure Fallback 2');

    console.log('  3. Remove Fallback 1');

    console.log('  4. Remove Fallback 2');

    console.log('  5. Retry / cooldown settings');

    console.log('  0. Back');

    console.log('');

    const choice = (await rl.question('Choose: ')).trim();

    if (choice === '0') {
      return;
    }

    if (choice === '1') {
      await configureFallbackSlot(rl, values, 1);

      continue;
    }

    if (choice === '2') {
      await configureFallbackSlot(rl, values, 2);

      continue;
    }

    if (choice === '3') {
      clearFallback(values, 1);

      saveEnv(values);

      console.log('');
      console.log('✓ Fallback 1 removed');
      console.log('');

      continue;
    }

    if (choice === '4') {
      clearFallback(values, 2);

      saveEnv(values);

      console.log('');
      console.log('✓ Fallback 2 removed');
      console.log('');

      continue;
    }

    if (choice === '5') {
      await fallbackPolicyWizard(rl, values);

      continue;
    }

    console.log('');
    console.log('⚠ Invalid selection');
  }
}

async function aiModelMenu(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  while (true) {
    console.log('');
    console.log('AI Model');

    console.log('──────────────────────────────────────');

    const llmProvider = values.get('TOOLNET_LLM_PROVIDER');

    const embeddingProvider = values.get('TOOLNET_EMBEDDING_PROVIDER');

    console.log(
      `  LLM       : ${
        llmProvider
          ? `${aiProviderLabel(llmProvider)} / ${
              values.get('TOOLNET_LLM_MODEL') || 'model not configured'
            }`
          : 'not configured'
      }`
    );

    console.log(
      `  Embedding : ${
        embeddingProvider
          ? `${embeddingProviderLabel(embeddingProvider)} / ${
              values.get('TOOLNET_EMBEDDING_MODEL') ||
              (embeddingProvider === 'local' ? 'local hash' : 'model not configured')
            }`
          : 'legacy/default'
      }`
    );

    console.log('');
    console.log('  1. Configure LLM');

    console.log('  2. Configure Embedding');

    console.log('  3. Use LLM provider credentials for Embedding');

    console.log('  4. Configure LLM Fallbacks');

    console.log('  0. Back');

    console.log('');

    const choice = (await rl.question('Choose: ')).trim();

    if (choice === '0') {
      return;
    }

    if (choice === '1') {
      await aiWizard(rl, values);

      continue;
    }

    if (choice === '2') {
      await embeddingWizard(rl, values);

      continue;
    }

    if (choice === '3') {
      await copyLlmToEmbedding(rl, values);

      continue;
    }

    if (choice === '4') {
      await fallbackWizard(rl, values);

      continue;
    }

    console.log('');
    console.log('⚠ Invalid selection');
  }
}

async function aiWizard(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  const original = new Map(values);

  while (true) {
    const selected = await chooseAiProvider(rl, currentAiProvider(values));

    if (selected === 'back') {
      return;
    }

    const definition = AI_WIZARD_PROVIDERS.find((provider) => provider.id === selected);

    if (!definition) {
      continue;
    }

    await configureAiProvider(rl, values, definition);

    if (!aiConfigComplete(values, definition)) {
      console.log('');
      console.log('⚠ AI configuration is incomplete.');
      console.log('');
      console.log('  1. Retry');
      console.log('  2. Save anyway');
      console.log('  3. Choose another provider');
      console.log('  4. Cancel');
      console.log('');

      const action = (await rl.question('Choose [1]: ')).trim() || '1';

      if (action === '2') {
        saveEnv(values);

        console.log('');
        console.log('⚠ AI configuration saved without validation');
        console.log(`  ${ENV_FILE}`);
        console.log('');

        return;
      }

      if (action === '3') {
        continue;
      }

      if (action === '4') {
        values.clear();

        for (const [key, value] of original) {
          values.set(key, value);
        }

        console.log('');
        console.log('AI changes cancelled.');
        console.log('');

        return;
      }

      continue;
    }

    const result = await testAiProvider(values);

    if (result.ok) {
      saveEnv(values);

      console.log(`✓ ${definition.label} configuration saved`);

      console.log(`  ${ENV_FILE}`);

      console.log('');

      return;
    }

    console.log('  1. Retry');
    console.log('  2. Save anyway');
    console.log('  3. Choose another provider');
    console.log('  4. Cancel');
    console.log('');

    const action = (await rl.question('Choose [1]: ')).trim() || '1';

    if (action === '2') {
      saveEnv(values);

      console.log('');
      console.log('⚠ AI configuration saved even though provider test failed');

      console.log(`  ${ENV_FILE}`);

      console.log('');

      return;
    }

    if (action === '3') {
      continue;
    }

    if (action === '4') {
      values.clear();

      for (const [key, value] of original) {
        values.set(key, value);
      }

      console.log('');
      console.log('AI changes cancelled.');
      console.log('');

      return;
    }
  }
}

function enableAutomaticAgentMemory(): void {
  try {
    const results = installAutoIntegrations();
    const installed = results.filter((item) => item.installed);

    if (installed.length === 0) {
      return;
    }

    console.log('');
    console.log('Automatic AI memory');

    for (const item of installed) {
      const name =
        item.agent === 'agy'
          ? 'Agy / Antigravity'
          : item.agent === 'opencode'
            ? 'OpenCode'
            : item.agent === 'codex'
              ? 'Codex'
              : item.agent;

      console.log(`  ✓ ${name}`);
    }
  } catch {
    // Optional integration. Setup itself must remain usable.
  }
}

function firstValue(values: Map<string, string>, ...keys: string[]): string | undefined {
  for (const key of keys) {
    const value = values.get(key)?.trim();
    if (value) {
      return value;
    }
  }
  return undefined;
}
function setCanonicalIfMissing(
  values: Map<string, string>,
  key: string,
  value: string | undefined
): void {
  if (value && !values.get(key)?.trim()) {
    values.set(key, value);
  }
}
/*
 * Phase 8 migration:
 *
 * Legacy environment names remain untouched for compatibility.
 * We only COPY their values into canonical TOOLNET_* keys.
 *
 * This means old installations upgrade safely without breaking.
 */
function migrateLegacyAiConfig(values: Map<string, string>): boolean {
  let migrated = false;
  const before = JSON.stringify([...values.entries()]);
  if (!values.get('TOOLNET_LLM_PROVIDER')?.trim()) {
    let provider: string | undefined;
    if (firstValue(values, 'GROQ_API_KEY')) {
      provider = 'groq';
    } else if (firstValue(values, 'DEEPSEEK_API_KEY')) {
      provider = 'deepseek';
    } else if (firstValue(values, 'NVIDIA_API_KEY', 'NVIDIA_NIM_API_KEY')) {
      provider = 'nvidia';
    } else if (firstValue(values, 'OPENROUTER_API_KEY')) {
      provider = 'openrouter';
    } else if (firstValue(values, 'ALIBABA_API_KEY', 'DASHSCOPE_API_KEY')) {
      provider = 'alibaba';
    } else if (firstValue(values, 'GEMINI_API_KEY', 'GOOGLE_API_KEY')) {
      provider = 'gemini';
    } else if (
      firstValue(values, 'CLOUDFLARE_API_TOKEN') &&
      firstValue(values, 'CLOUDFLARE_ACCOUNT_ID')
    ) {
      provider = 'cloudflare';
    } else if (firstValue(values, 'HF_TOKEN')) {
      provider = 'huggingface';
    } else if (firstValue(values, 'OLLAMA_MODEL', 'OLLAMA_BASE_URL')) {
      provider = 'ollama';
    } else if (firstValue(values, 'OPENAI_API_KEY', 'MODEL_API_KEY')) {
      provider = 'openai-compatible';
    }
    if (provider) {
      values.set('TOOLNET_LLM_PROVIDER', provider);
    }
  }
  const provider = values.get('TOOLNET_LLM_PROVIDER')?.trim();
  switch (provider) {
    case 'groq':
      setCanonicalIfMissing(values, 'TOOLNET_LLM_API_KEY', firstValue(values, 'GROQ_API_KEY'));
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_BASE_URL',
        firstValue(values, 'GROQ_BASE_URL') || 'https://api.groq.com/openai/v1'
      );
      setCanonicalIfMissing(values, 'TOOLNET_LLM_MODEL', firstValue(values, 'GROQ_MODEL'));
      break;
    case 'deepseek':
      setCanonicalIfMissing(values, 'TOOLNET_LLM_API_KEY', firstValue(values, 'DEEPSEEK_API_KEY'));
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_BASE_URL',
        firstValue(values, 'DEEPSEEK_BASE_URL') || 'https://api.deepseek.com'
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_MODEL',
        firstValue(values, 'DEEPSEEK_MODEL') || 'deepseek-v4-flash'
      );
      break;
    case 'nvidia':
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_API_KEY',
        firstValue(values, 'NVIDIA_API_KEY', 'NVIDIA_NIM_API_KEY')
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_BASE_URL',
        firstValue(values, 'NVIDIA_BASE_URL', 'NVIDIA_NIM_BASE_URL') ||
          'https://integrate.api.nvidia.com/v1'
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_MODEL',
        firstValue(values, 'NVIDIA_MODEL', 'NVIDIA_NIM_MODEL')
      );
      break;
    case 'openrouter':
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_API_KEY',
        firstValue(values, 'OPENROUTER_API_KEY')
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_BASE_URL',
        firstValue(values, 'OPENROUTER_BASE_URL') || 'https://openrouter.ai/api/v1'
      );
      setCanonicalIfMissing(values, 'TOOLNET_LLM_MODEL', firstValue(values, 'OPENROUTER_MODEL'));
      break;
    case 'alibaba':
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_API_KEY',
        firstValue(values, 'ALIBABA_API_KEY', 'DASHSCOPE_API_KEY')
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_BASE_URL',
        firstValue(values, 'ALIBABA_BASE_URL', 'DASHSCOPE_BASE_URL')
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_MODEL',
        firstValue(values, 'ALIBABA_MODEL', 'DASHSCOPE_MODEL')
      );
      break;
    case 'gemini':
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_API_KEY',
        firstValue(values, 'GEMINI_API_KEY', 'GOOGLE_API_KEY')
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_BASE_URL',
        firstValue(values, 'GEMINI_BASE_URL') || 'https://generativelanguage.googleapis.com/v1beta'
      );
      setCanonicalIfMissing(values, 'TOOLNET_LLM_MODEL', firstValue(values, 'GEMINI_MODEL'));
      break;
    case 'huggingface':
      setCanonicalIfMissing(values, 'TOOLNET_LLM_API_KEY', firstValue(values, 'HF_TOKEN'));
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_BASE_URL',
        firstValue(values, 'HF_INFERENCE_BASE_URL') || 'https://router.huggingface.co/v1'
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_MODEL',
        firstValue(values, 'HF_LLM_MODEL', 'HF_MODEL')
      );
      break;
    case 'ollama':
      setCanonicalIfMissing(values, 'TOOLNET_LLM_API_KEY', firstValue(values, 'OLLAMA_API_KEY'));
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_BASE_URL',
        firstValue(values, 'OLLAMA_BASE_URL') || 'http://127.0.0.1:11434/v1'
      );
      setCanonicalIfMissing(values, 'TOOLNET_LLM_MODEL', firstValue(values, 'OLLAMA_MODEL'));
      break;
    case 'cloudflare':
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_API_KEY',
        firstValue(values, 'CLOUDFLARE_API_TOKEN')
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_ACCOUNT_ID',
        firstValue(values, 'CLOUDFLARE_ACCOUNT_ID')
      );
      setCanonicalIfMissing(values, 'TOOLNET_LLM_MODEL', firstValue(values, 'CLOUDFLARE_MODEL'));
      break;
    case 'openai-compatible':
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_API_KEY',
        firstValue(values, 'OPENAI_API_KEY', 'MODEL_API_KEY')
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_BASE_URL',
        firstValue(values, 'OPENAI_BASE_URL', 'MODEL_BASE_URL')
      );
      setCanonicalIfMissing(
        values,
        'TOOLNET_LLM_MODEL',
        firstValue(values, 'OPENAI_MODEL', 'MODEL_NAME')
      );
      break;
  }
  /*
   * Existing HF embedding configuration
   * becomes canonical embedding config.
   */
  if (!values.get('TOOLNET_EMBEDDING_PROVIDER')?.trim() && firstValue(values, 'HF_TOKEN')) {
    values.set('TOOLNET_EMBEDDING_PROVIDER', 'huggingface');
    setCanonicalIfMissing(values, 'TOOLNET_EMBEDDING_API_KEY', firstValue(values, 'HF_TOKEN'));
    setCanonicalIfMissing(
      values,
      'TOOLNET_EMBEDDING_MODEL',
      firstValue(values, 'HF_EMBEDDING_MODEL') || 'sentence-transformers/all-MiniLM-L6-v2'
    );
  }
  const after = JSON.stringify([...values.entries()]);
  migrated = before !== after;
  return migrated;
}
function setupSummaryValue(value: string | undefined, fallback = 'not configured'): string {
  return value?.trim() || fallback;
}
function printFinalSetupSummary(values: Map<string, string>): void {
  const storage = providerLabel(providerFrom(values));
  const llmProvider = values.get('TOOLNET_LLM_PROVIDER');
  const llmModel = values.get('TOOLNET_LLM_MODEL');
  const embeddingProvider = values.get('TOOLNET_EMBEDDING_PROVIDER');
  const embeddingModel = values.get('TOOLNET_EMBEDDING_MODEL');
  const fallback1 = values.get('TOOLNET_LLM_FALLBACK_1_PROVIDER');
  const fallback2 = values.get('TOOLNET_LLM_FALLBACK_2_PROVIDER');

  console.log('');
  console.log('◇ ToolNet Memory Setup');
  console.log('');
  console.log('◆ Configuration');
  console.log('│');
  console.log(`├ ◆ Storage    — ${storage}`);
  console.log(
    `├ ◆ LLM        — ${
      llmProvider
        ? `${aiProviderLabel(llmProvider)} / ${setupSummaryValue(llmModel)}`
        : 'not configured'
    }`
  );
  console.log(
    `├ ◇ Fallback 1 — ${
      fallback1
        ? `${aiProviderLabel(fallback1)} / ${setupSummaryValue(
            values.get('TOOLNET_LLM_FALLBACK_1_MODEL')
          )}`
        : 'none'
    }`
  );
  console.log(
    `├ ◇ Fallback 2 — ${
      fallback2
        ? `${aiProviderLabel(fallback2)} / ${setupSummaryValue(
            values.get('TOOLNET_LLM_FALLBACK_2_MODEL')
          )}`
        : 'none'
    }`
  );
  console.log(
    `├ ◆ Embedding  — ${
      embeddingProvider
        ? `${
            embeddingProvider === 'local'
              ? 'Local / Hash'
              : embeddingProviderLabel(embeddingProvider)
          } / ${setupSummaryValue(
            embeddingModel,
            embeddingProvider === 'local' ? 'local hash' : 'not configured'
          )}`
        : 'legacy/default'
    }`
  );
  console.log('│');
  console.log(`├ ◆ Config      — ${ENV_FILE}`);
  console.log(`├ ◆ Permissions — ${fs.statSync(ENV_FILE).mode.toString(8).slice(-3)}`);
  console.log('├ ◆ Secrets     — hidden');
  console.log('├ ◆ Config mode — canonical TOOLNET_*');
  console.log('│');
  console.log('└ ◆ Setup complete');
}
function ensureDefaults(values: Map<string, string>): void {
  migrateLegacyAiConfig(values);
  if (!values.has('TOOLNET_LLM_FALLBACK_COOLDOWN_MS')) {
    values.set('TOOLNET_LLM_FALLBACK_COOLDOWN_MS', '60000');
  }
  if (!values.has('TOOLNET_LLM_MAX_RETRIES')) {
    values.set('TOOLNET_LLM_MAX_RETRIES', '1');
  }

  if (!values.has('MEMORY_STORAGE_PROVIDER')) {
    values.set('MEMORY_STORAGE_PROVIDER', providerFrom(values));
  }

  if (!values.has('MEMORY_LOCAL_CACHE_MB')) {
    values.set('MEMORY_LOCAL_CACHE_MB', '200');
  }

  if (!values.has('MEMORY_AUTO_CAPTURE')) {
    values.set('MEMORY_AUTO_CAPTURE', 'true');
  }

  if (!values.has('MEMORY_AUTO_RETRIEVE')) {
    values.set('MEMORY_AUTO_RETRIEVE', 'true');
  }

  if (!values.has('MEMORY_AUTO_SUMMARIZE')) {
    values.set('MEMORY_AUTO_SUMMARIZE', 'true');
  }

  if (!values.has('MEMORY_AUTO_SYNC')) {
    values.set('MEMORY_AUTO_SYNC', 'true');
  }

  if (!values.has('MEMORY_MAX_CANDIDATES')) {
    values.set('MEMORY_MAX_CANDIDATES', '50');
  }

  if (!values.has('MEMORY_RERANK_TOP')) {
    values.set('MEMORY_RERANK_TOP', '10');
  }

  if (!values.has('MEMORY_FINAL_CONTEXT')) {
    values.set('MEMORY_FINAL_CONTEXT', '5');
  }

  if (!values.has('MEMORY_TOKEN_BUDGET')) {
    values.set('MEMORY_TOKEN_BUDGET', '2000');
  }

  if (!values.has('TOOLNET_SESSION_LEARNING')) {
    values.set('TOOLNET_SESSION_LEARNING', '1');
  }

  if (!values.has('TOOLNET_WORK_CONTINUITY')) {
    values.set('TOOLNET_WORK_CONTINUITY', '1');
  }

  if (!values.has('TOOLNET_SEMANTIC_CONTINUITY')) {
    values.set('TOOLNET_SEMANTIC_CONTINUITY', '1');
  }

  if (!values.has('TOOLNET_SMART_HANDOFF')) {
    values.set('TOOLNET_SMART_HANDOFF', '1');
  }
}

async function nonInteractiveSetup(values: Map<string, string>, exists: boolean): Promise<void> {
  ensureDefaults(values);

  if (!exists) {
    saveEnv(values);
  }

  console.log('');
  console.log('◇ ToolNet Memory Setup');
  console.log('');
  console.log('◆ Non-interactive mode');
  console.log('│');
  console.log(`├ ◆ Config   — ${ENV_FILE}`);
  console.log(`├ ◆ Storage  — ${providerLabel(providerFrom(values))}`);
  console.log('│');
  console.log('└ ◇ Run toolnet-memory setup from an interactive terminal');
}

async function main(): Promise<void> {
  const exists = fs.existsSync(ENV_FILE);

  const original = exists ? parseEnv(fs.readFileSync(ENV_FILE, 'utf8')) : new Map<string, string>();

  const values = new Map(original);

  ensureDefaults(values);

  if (!input.isTTY || !output.isTTY) {
    await nonInteractiveSetup(values, exists);
    return;
  }

  const rl = readline.createInterface({
    input,
    output,
  });

  let dirty = false;

  try {
    while (true) {
      printHeader();
      printCurrentStatus(values);

      const choice = await mainMenu(rl);

      if (choice === 'storage') {
        const before = JSON.stringify([...values.entries()]);

        await storageWizard(rl, values);

        dirty = dirty || before !== JSON.stringify([...values.entries()]);
        continue;
      }

      if (choice === 'ai') {
        const before = JSON.stringify([...values.entries()]);

        await aiModelMenu(rl, values);

        dirty = dirty || before !== JSON.stringify([...values.entries()]);

        continue;
      }

      if (choice === 'exit') {
        if (!dirty) {
          console.log('');
          console.log('No changes made.');
          return;
        }

        console.log('');
        const confirm = (await rl.question('Discard unsaved changes? (y/N): '))
          .trim()
          .toLowerCase();

        if (confirm === 'y' || confirm === 'yes') {
          console.log('');
          console.log('Changes discarded.');
          return;
        }

        continue;
      }

      saveEnv(values);
      if (!storageConfigured(values)) {
        console.log('');
        console.log('⚠ Storage configuration is incomplete.');
      }
      enableAutomaticAgentMemory();
      printFinalSetupSummary(values);
      console.log('');
      console.log('Validate:');
      console.log('  toolnet-memory provider:status');
      console.log('  toolnet-memory provider:test');
      console.log('  toolnet-memory doctor');
      console.log('');
      return;
    }
  } finally {
    rl.close();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
