import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

import { installAutoIntegrations } from './auto-integrate.js';

const CONFIG_DIR = path.join(os.homedir(), '.config', 'toolnet-memory');
const ENV_FILE = path.join(CONFIG_DIR, '.env');

type StorageProviderName = 'r2' | 's3' | 'local' | 'huggingface';

type MainMenuChoice = 'storage' | 'ai' | 'finish' | 'exit';

const KNOWN_ENV_KEYS = new Set([
  'MEMORY_STORAGE_PROVIDER',

  'R2_ACCOUNT_ID',
  'R2_BUCKET',
  'R2_ACCESS_KEY_ID',
  'R2_SECRET_ACCESS_KEY',

  'S3_ENDPOINT',
  'S3_REGION',
  'S3_BUCKET',
  'S3_ACCESS_KEY_ID',
  'S3_SECRET_ACCESS_KEY',
  'S3_FORCE_PATH_STYLE',

  'HF_NAMESPACE',
  'HF_BUCKET',
  'HF_S3_ACCESS_KEY_ID',
  'HF_S3_SECRET_ACCESS_KEY',
  'HF_URL',

  'HF_TOKEN',
  'HF_EMBEDDING_MODEL',

  'MEMORY_LOCAL_STORAGE_PATH',
  'MEMORY_LOCAL_CACHE_MB',

  'MEMORY_AUTO_CAPTURE',
  'MEMORY_AUTO_RETRIEVE',
  'MEMORY_AUTO_SUMMARIZE',
  'MEMORY_AUTO_SYNC',

  'MEMORY_MAX_CANDIDATES',
  'MEMORY_RERANK_TOP',
  'MEMORY_FINAL_CONTEXT',
  'MEMORY_TOKEN_BUDGET',

  'TOOLNET_SESSION_LEARNING',
  'TOOLNET_WORK_CONTINUITY',
  'TOOLNET_SEMANTIC_CONTINUITY',
  'TOOLNET_SMART_HANDOFF',
]);

function parseEnv(text: string): Map<string, string> {
  const values = new Map<string, string>();

  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();

    if (!line || line.startsWith('#')) {
      continue;
    }

    const index = line.indexOf('=');

    if (index === -1) {
      continue;
    }

    const key = line.slice(0, index).trim();
    const value = line.slice(index + 1).trim();

    if (key) {
      values.set(key, value);
    }
  }

  return values;
}

function providerFrom(values: Map<string, string>): StorageProviderName {
  const explicit = values.get('MEMORY_STORAGE_PROVIDER')?.trim();

  if (
    explicit === 'r2' ||
    explicit === 's3' ||
    explicit === 'local' ||
    explicit === 'huggingface'
  ) {
    return explicit;
  }

  if (values.get('R2_ACCOUNT_ID') && values.get('R2_BUCKET')) {
    return 'r2';
  }

  if (values.get('S3_BUCKET')) {
    return 's3';
  }

  if (values.get('HF_BUCKET') && values.get('HF_S3_ACCESS_KEY_ID')) {
    return 'huggingface';
  }

  if (values.get('MEMORY_LOCAL_STORAGE_PATH')) {
    return 'local';
  }

  return 'r2';
}

function providerLabel(provider: StorageProviderName): string {
  switch (provider) {
    case 'r2':
      return 'Cloudflare R2';

    case 's3':
      return 'S3 / S3-compatible';

    case 'huggingface':
      return 'Hugging Face S3';

    case 'local':
      return 'Local';

    default:
      return provider;
  }
}

function requiredFor(provider: StorageProviderName): string[] {
  switch (provider) {
    case 'r2':
      return ['R2_ACCOUNT_ID', 'R2_BUCKET', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY'];

    case 's3':
      return ['S3_BUCKET', 'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY'];

    case 'huggingface':
      return ['HF_BUCKET', 'HF_S3_ACCESS_KEY_ID', 'HF_S3_SECRET_ACCESS_KEY'];

    case 'local':
      return [];

    default:
      return [];
  }
}

function storageConfigured(values: Map<string, string>): boolean {
  const provider = providerFrom(values);

  if (provider === 'local') {
    return true;
  }

  return requiredFor(provider).every((key) => Boolean(values.get(key)?.trim()));
}

function masked(value: string | undefined): string {
  if (!value) {
    return 'not configured';
  }

  if (value.length <= 8) {
    return 'configured';
  }

  return `${value.slice(0, 4)}••••${value.slice(-3)}`;
}

function renderEnv(values: Map<string, string>): string {
  const provider = providerFrom(values);

  const lines = [
    '# ==========================================================',
    '# TOOLNET MEMORY',
    '# Generated by: toolnet-memory setup',
    '# Do not commit this file.',
    '# ==========================================================',
    '',
    `MEMORY_STORAGE_PROVIDER=${provider}`,
    '',
    '# ----------------------------------------------------------',
    '# Cloudflare R2',
    '# ----------------------------------------------------------',
    `R2_ACCOUNT_ID=${values.get('R2_ACCOUNT_ID') ?? ''}`,
    `R2_BUCKET=${values.get('R2_BUCKET') ?? 'toolnet-memory'}`,
    `R2_ACCESS_KEY_ID=${values.get('R2_ACCESS_KEY_ID') ?? ''}`,
    `R2_SECRET_ACCESS_KEY=${values.get('R2_SECRET_ACCESS_KEY') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# Generic S3 / S3-compatible',
    '# ----------------------------------------------------------',
    `S3_ENDPOINT=${values.get('S3_ENDPOINT') ?? ''}`,
    `S3_REGION=${values.get('S3_REGION') ?? 'us-east-1'}`,
    `S3_BUCKET=${values.get('S3_BUCKET') ?? 'toolnet-memory'}`,
    `S3_ACCESS_KEY_ID=${values.get('S3_ACCESS_KEY_ID') ?? ''}`,
    `S3_SECRET_ACCESS_KEY=${values.get('S3_SECRET_ACCESS_KEY') ?? ''}`,
    `S3_FORCE_PATH_STYLE=${values.get('S3_FORCE_PATH_STYLE') ?? 'false'}`,
    '',
    '# ----------------------------------------------------------',
    '# Hugging Face S3',
    '# ----------------------------------------------------------',
    `HF_NAMESPACE=${values.get('HF_NAMESPACE') ?? ''}`,
    `HF_BUCKET=${values.get('HF_BUCKET') ?? 'toolnet-memory'}`,
    `HF_S3_ACCESS_KEY_ID=${values.get('HF_S3_ACCESS_KEY_ID') ?? ''}`,
    `HF_S3_SECRET_ACCESS_KEY=${values.get('HF_S3_SECRET_ACCESS_KEY') ?? ''}`,
    `HF_URL=${values.get('HF_URL') ?? ''}`,
    '',
    '# ----------------------------------------------------------',
    '# Embedding - legacy/current compatibility',
    '# ----------------------------------------------------------',
    `HF_TOKEN=${values.get('HF_TOKEN') ?? ''}`,
    `HF_EMBEDDING_MODEL=${
      values.get('HF_EMBEDDING_MODEL') ?? 'sentence-transformers/all-MiniLM-L6-v2'
    }`,
    '',
    '# ----------------------------------------------------------',
    '# Local storage/cache',
    '# ----------------------------------------------------------',
    `MEMORY_LOCAL_STORAGE_PATH=${values.get('MEMORY_LOCAL_STORAGE_PATH') ?? ''}`,
    `MEMORY_LOCAL_CACHE_MB=${values.get('MEMORY_LOCAL_CACHE_MB') ?? '200'}`,
    '',
    '# ----------------------------------------------------------',
    '# Automation',
    '# ----------------------------------------------------------',
    `MEMORY_AUTO_CAPTURE=${values.get('MEMORY_AUTO_CAPTURE') ?? 'true'}`,
    `MEMORY_AUTO_RETRIEVE=${values.get('MEMORY_AUTO_RETRIEVE') ?? 'true'}`,
    `MEMORY_AUTO_SUMMARIZE=${values.get('MEMORY_AUTO_SUMMARIZE') ?? 'true'}`,
    `MEMORY_AUTO_SYNC=${values.get('MEMORY_AUTO_SYNC') ?? 'true'}`,
    '',
    '# ----------------------------------------------------------',
    '# Retrieval',
    '# ----------------------------------------------------------',
    `MEMORY_MAX_CANDIDATES=${values.get('MEMORY_MAX_CANDIDATES') ?? '50'}`,
    `MEMORY_RERANK_TOP=${values.get('MEMORY_RERANK_TOP') ?? '10'}`,
    `MEMORY_FINAL_CONTEXT=${values.get('MEMORY_FINAL_CONTEXT') ?? '5'}`,
    `MEMORY_TOKEN_BUDGET=${values.get('MEMORY_TOKEN_BUDGET') ?? '2000'}`,
    '',
    '# ----------------------------------------------------------',
    '# Automatic Session Memory',
    '# ----------------------------------------------------------',
    `TOOLNET_SESSION_LEARNING=${values.get('TOOLNET_SESSION_LEARNING') ?? '1'}`,
    `TOOLNET_WORK_CONTINUITY=${values.get('TOOLNET_WORK_CONTINUITY') ?? '1'}`,
    `TOOLNET_SEMANTIC_CONTINUITY=${values.get('TOOLNET_SEMANTIC_CONTINUITY') ?? '1'}`,
    `TOOLNET_SMART_HANDOFF=${values.get('TOOLNET_SMART_HANDOFF') ?? '1'}`,
  ];

  const unknown = [...values.entries()].filter(([key]) => !KNOWN_ENV_KEYS.has(key));

  if (unknown.length > 0) {
    lines.push(
      '',
      '# ----------------------------------------------------------',
      '# Preserved settings',
      '# ----------------------------------------------------------'
    );

    for (const [key, value] of unknown) {
      lines.push(`${key}=${value}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function saveEnv(values: Map<string, string>): void {
  fs.mkdirSync(CONFIG_DIR, {
    recursive: true,
    mode: 0o700,
  });

  const temp = `${ENV_FILE}.tmp-${process.pid}`;

  fs.writeFileSync(temp, renderEnv(values), {
    encoding: 'utf8',
    mode: 0o600,
  });

  fs.renameSync(temp, ENV_FILE);

  fs.chmodSync(CONFIG_DIR, 0o700);
  fs.chmodSync(ENV_FILE, 0o600);
}

function setIfEntered(
  values: Map<string, string>,
  key: string,
  value: string,
  fallback?: string
): void {
  const normalized = value.trim();

  if (normalized) {
    values.set(key, normalized);
    return;
  }

  if (!values.get(key) && fallback !== undefined) {
    values.set(key, fallback);
  }
}

async function secretQuestion(rl: readline.Interface, label: string): Promise<string> {
  if (!input.isTTY) {
    return '';
  }

  rl.pause();

  output.write(label);

  return new Promise((resolve) => {
    let value = '';
    let finished = false;

    const finish = () => {
      if (finished) {
        return;
      }

      finished = true;

      input.off('data', onData);
      input.setRawMode?.(false);
      input.pause();

      output.write('\n');

      rl.resume();

      resolve(value);
    };

    const onData = (chunk: Buffer) => {
      for (const ch of chunk.toString('utf8')) {
        if (ch === '\r' || ch === '\n') {
          finish();
          return;
        }

        if (ch === '\u0003') {
          input.off('data', onData);
          input.setRawMode?.(false);
          output.write('\n');
          process.exit(130);
        }

        if (ch === '\u007f') {
          value = value.slice(0, -1);
          continue;
        }

        value += ch;
      }
    };

    input.resume();
    input.setRawMode?.(true);
    input.on('data', onData);
  });
}

function printHeader(): void {
  console.log('');
  console.log('╔══════════════════════════════════════╗');
  console.log('║         TOOLNET MEMORY SETUP         ║');
  console.log('╚══════════════════════════════════════╝');
  console.log('');
}

function printCurrentStatus(values: Map<string, string>): void {
  const provider = providerFrom(values);

  console.log('Current configuration');
  console.log('──────────────────────────────────────');
  console.log(
    `Storage : ${providerLabel(provider)} ${storageConfigured(values) ? '✓' : '⚠ incomplete'}`
  );

  const llmProvider = values.get('TOOLNET_LLM_PROVIDER');
  const embeddingProvider = values.get('TOOLNET_EMBEDDING_PROVIDER');

  console.log(`LLM     : ${llmProvider || 'not configured'}`);
  console.log(`Embedding: ${embeddingProvider || 'legacy/default'}`);
  console.log('');
}

async function mainMenu(rl: readline.Interface): Promise<MainMenuChoice> {
  console.log('Setup');
  console.log('──────────────────────────────────────');
  console.log('  1. Storage');
  console.log('  2. AI Model');
  console.log('  3. Finish & Save');
  console.log('  0. Exit without saving');
  console.log('');

  const answer = (await rl.question('Choose [1-3]: ')).trim();

  if (answer === '1') {
    return 'storage';
  }

  if (answer === '2') {
    return 'ai';
  }

  if (answer === '0') {
    return 'exit';
  }

  if (answer === '3') {
    return 'finish';
  }

  return 'finish';
}

async function chooseStorageProvider(
  rl: readline.Interface,
  current: StorageProviderName
): Promise<StorageProviderName | 'back'> {
  console.log('');
  console.log('Storage');
  console.log('──────────────────────────────────────');
  console.log(`  1. Cloudflare R2${current === 'r2' ? '  ✓ current' : ''}`);
  console.log(`  2. S3 / S3-compatible${current === 's3' ? '  ✓ current' : ''}`);
  console.log(`  3. Hugging Face S3${current === 'huggingface' ? '  ✓ current' : ''}`);
  console.log(`  4. Local${current === 'local' ? '  ✓ current' : ''}`);
  console.log('');
  console.log('  0. Back');
  console.log('');

  const answer = (await rl.question('Choose storage: ')).trim();

  if (answer === '0') {
    return 'back';
  }

  if (answer === '2') {
    return 's3';
  }

  if (answer === '3') {
    return 'huggingface';
  }

  if (answer === '4') {
    return 'local';
  }

  return 'r2';
}

async function configureR2(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  console.log('');
  console.log('Cloudflare R2');
  console.log('──────────────────────────────────────');

  const accountId = await rl.question(
    values.get('R2_ACCOUNT_ID') ? `ACCOUNT ID [${values.get('R2_ACCOUNT_ID')}]: ` : 'ACCOUNT ID: '
  );

  const access = await rl.question(
    values.get('R2_ACCESS_KEY_ID')
      ? `ACCESS KEY ID [${masked(values.get('R2_ACCESS_KEY_ID'))}]: `
      : 'ACCESS KEY ID: '
  );

  const bucket = await rl.question(`BUCKET [${values.get('R2_BUCKET') || 'toolnet-memory'}]: `);

  setIfEntered(values, 'R2_ACCOUNT_ID', accountId);
  setIfEntered(values, 'R2_ACCESS_KEY_ID', access);
  setIfEntered(values, 'R2_BUCKET', bucket, 'toolnet-memory');

  const secret = await secretQuestion(
    rl,
    values.get('R2_SECRET_ACCESS_KEY')
      ? 'SECRET ACCESS KEY [configured, Enter = keep]: '
      : 'SECRET ACCESS KEY: '
  );

  if (secret.trim()) {
    values.set('R2_SECRET_ACCESS_KEY', secret.trim());
  }
}

async function configureS3(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  console.log('');
  console.log('S3 / S3-compatible');
  console.log('──────────────────────────────────────');

  const endpoint = await rl.question(
    values.get('S3_ENDPOINT')
      ? `URL / ENDPOINT [${values.get('S3_ENDPOINT')}]: `
      : 'URL / ENDPOINT [blank = AWS S3]: '
  );

  const region = await rl.question(`REGION [${values.get('S3_REGION') || 'us-east-1'}]: `);

  const access = await rl.question(
    values.get('S3_ACCESS_KEY_ID')
      ? `ACCESS KEY ID [${masked(values.get('S3_ACCESS_KEY_ID'))}]: `
      : 'ACCESS KEY ID: '
  );

  const bucket = await rl.question(`BUCKET [${values.get('S3_BUCKET') || 'toolnet-memory'}]: `);

  if (endpoint.trim()) {
    values.set('S3_ENDPOINT', endpoint.trim());
  }

  setIfEntered(values, 'S3_REGION', region, 'us-east-1');
  setIfEntered(values, 'S3_ACCESS_KEY_ID', access);
  setIfEntered(values, 'S3_BUCKET', bucket, 'toolnet-memory');

  const secret = await secretQuestion(
    rl,
    values.get('S3_SECRET_ACCESS_KEY')
      ? 'SECRET ACCESS KEY [configured, Enter = keep]: '
      : 'SECRET ACCESS KEY: '
  );

  if (secret.trim()) {
    values.set('S3_SECRET_ACCESS_KEY', secret.trim());
  }
}

async function configureHuggingFace(
  rl: readline.Interface,
  values: Map<string, string>
): Promise<void> {
  console.log('');
  console.log('Hugging Face S3');
  console.log('──────────────────────────────────────');

  const access = await rl.question(
    values.get('HF_S3_ACCESS_KEY_ID')
      ? `ACCESS KEY ID [${masked(values.get('HF_S3_ACCESS_KEY_ID'))}]: `
      : 'ACCESS KEY ID: '
  );

  const bucket = await rl.question(`BUCKET [${values.get('HF_BUCKET') || 'toolnet-memory'}]: `);

  const url = await rl.question(
    values.get('HF_URL') ? `URL [${values.get('HF_URL')}]: ` : 'URL [optional]: '
  );

  setIfEntered(values, 'HF_S3_ACCESS_KEY_ID', access);
  setIfEntered(values, 'HF_BUCKET', bucket, 'toolnet-memory');
  setIfEntered(values, 'HF_URL', url);

  const secret = await secretQuestion(
    rl,
    values.get('HF_S3_SECRET_ACCESS_KEY')
      ? 'SECRET ACCESS KEY [configured, Enter = keep]: '
      : 'SECRET ACCESS KEY: '
  );

  if (secret.trim()) {
    values.set('HF_S3_SECRET_ACCESS_KEY', secret.trim());
  }
}

async function configureLocal(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  console.log('');
  console.log('Local Storage');
  console.log('──────────────────────────────────────');

  const defaultPath =
    values.get('MEMORY_LOCAL_STORAGE_PATH') ??
    path.join(os.homedir(), '.local', 'share', 'toolnet-memory');

  const storagePath = await rl.question(`LOCAL PATH [${defaultPath}]: `);

  setIfEntered(values, 'MEMORY_LOCAL_STORAGE_PATH', storagePath, defaultPath);
}

async function storageWizard(rl: readline.Interface, values: Map<string, string>): Promise<void> {
  const current = providerFrom(values);

  const provider = await chooseStorageProvider(rl, current);

  if (provider === 'back') {
    return;
  }

  const snapshot = new Map(values);

  values.set('MEMORY_STORAGE_PROVIDER', provider);

  if (provider === 'r2') {
    await configureR2(rl, values);
  } else if (provider === 's3') {
    await configureS3(rl, values);
  } else if (provider === 'huggingface') {
    await configureHuggingFace(rl, values);
  } else {
    await configureLocal(rl, values);
  }

  const missing = requiredFor(provider).filter((key) => !values.get(key)?.trim());

  if (missing.length === 0) {
    console.log('');
    console.log(`✓ ${providerLabel(provider)} configuration ready`);
    console.log('');
    return;
  }

  console.log('');
  console.log('⚠ Missing required fields:');

  for (const key of missing) {
    console.log(`  - ${key}`);
  }

  console.log('');
  console.log('  1. Retry');
  console.log('  2. Save anyway');
  console.log('  3. Cancel changes');
  console.log('');

  const action = (await rl.question('Choose [1]: ')).trim() || '1';

  if (action === '3') {
    values.clear();

    for (const [key, value] of snapshot.entries()) {
      values.set(key, value);
    }

    console.log('');
    console.log('Storage changes cancelled.');
    console.log('');
    return;
  }

  if (action === '1') {
    await storageWizard(rl, values);
    return;
  }

  console.log('');
  console.log('⚠ Storage saved with incomplete configuration.');
  console.log('');
}

async function aiWizardPlaceholder(rl: readline.Interface): Promise<void> {
  console.log('');
  console.log('AI Model');
  console.log('──────────────────────────────────────');
  console.log('');
  console.log('Phase 1 installs the setup framework.');
  console.log('Multi-provider AI configuration will be added in Phase 3/4.');
  console.log('');
  console.log('Planned providers:');
  console.log('  1. OpenAI-compatible');
  console.log('  2. Alibaba / DashScope');
  console.log('  3. OpenRouter');
  console.log('  4. Groq');
  console.log('  5. Gemini');
  console.log('  6. Hugging Face');
  console.log('  7. Ollama / Local');
  console.log('  8. Custom endpoint');
  console.log('  9. Cloudflare');
  console.log('');

  await rl.question('Press Enter to go back...');
  console.log('');
}

function enableAutomaticAgentMemory(): void {
  try {
    const results = installAutoIntegrations();
    const installed = results.filter((item) => item.installed);

    if (installed.length === 0) {
      return;
    }

    console.log('');
    console.log('Automatic AI memory');

    for (const item of installed) {
      const name =
        item.agent === 'agy'
          ? 'Agy / Antigravity'
          : item.agent === 'opencode'
            ? 'OpenCode'
            : item.agent === 'codex'
              ? 'Codex'
              : item.agent;

      console.log(`  ✓ ${name}`);
    }
  } catch {
    // Optional integration. Setup itself must remain usable.
  }
}

function ensureDefaults(values: Map<string, string>): void {
  if (!values.has('MEMORY_STORAGE_PROVIDER')) {
    values.set('MEMORY_STORAGE_PROVIDER', providerFrom(values));
  }

  if (!values.has('MEMORY_LOCAL_CACHE_MB')) {
    values.set('MEMORY_LOCAL_CACHE_MB', '200');
  }

  if (!values.has('MEMORY_AUTO_CAPTURE')) {
    values.set('MEMORY_AUTO_CAPTURE', 'true');
  }

  if (!values.has('MEMORY_AUTO_RETRIEVE')) {
    values.set('MEMORY_AUTO_RETRIEVE', 'true');
  }

  if (!values.has('MEMORY_AUTO_SUMMARIZE')) {
    values.set('MEMORY_AUTO_SUMMARIZE', 'true');
  }

  if (!values.has('MEMORY_AUTO_SYNC')) {
    values.set('MEMORY_AUTO_SYNC', 'true');
  }

  if (!values.has('MEMORY_MAX_CANDIDATES')) {
    values.set('MEMORY_MAX_CANDIDATES', '50');
  }

  if (!values.has('MEMORY_RERANK_TOP')) {
    values.set('MEMORY_RERANK_TOP', '10');
  }

  if (!values.has('MEMORY_FINAL_CONTEXT')) {
    values.set('MEMORY_FINAL_CONTEXT', '5');
  }

  if (!values.has('MEMORY_TOKEN_BUDGET')) {
    values.set('MEMORY_TOKEN_BUDGET', '2000');
  }

  if (!values.has('TOOLNET_SESSION_LEARNING')) {
    values.set('TOOLNET_SESSION_LEARNING', '1');
  }

  if (!values.has('TOOLNET_WORK_CONTINUITY')) {
    values.set('TOOLNET_WORK_CONTINUITY', '1');
  }

  if (!values.has('TOOLNET_SEMANTIC_CONTINUITY')) {
    values.set('TOOLNET_SEMANTIC_CONTINUITY', '1');
  }

  if (!values.has('TOOLNET_SMART_HANDOFF')) {
    values.set('TOOLNET_SMART_HANDOFF', '1');
  }
}

async function nonInteractiveSetup(values: Map<string, string>, exists: boolean): Promise<void> {
  ensureDefaults(values);

  if (!exists) {
    saveEnv(values);
  }

  console.log('TOOLNET MEMORY SETUP');
  console.log('');
  console.log('Interactive terminal not detected.');
  console.log(`Config: ${ENV_FILE}`);
  console.log(`Storage: ${providerLabel(providerFrom(values))}`);
  console.log('');
  console.log('Run from an interactive terminal to configure providers:');
  console.log('  toolnet-memory setup');
}

async function main(): Promise<void> {
  const exists = fs.existsSync(ENV_FILE);

  const original = exists ? parseEnv(fs.readFileSync(ENV_FILE, 'utf8')) : new Map<string, string>();

  const values = new Map(original);

  ensureDefaults(values);

  if (!input.isTTY || !output.isTTY) {
    await nonInteractiveSetup(values, exists);
    return;
  }

  const rl = readline.createInterface({
    input,
    output,
  });

  let dirty = false;

  try {
    while (true) {
      printHeader();
      printCurrentStatus(values);

      const choice = await mainMenu(rl);

      if (choice === 'storage') {
        const before = JSON.stringify([...values.entries()]);

        await storageWizard(rl, values);

        dirty = dirty || before !== JSON.stringify([...values.entries()]);
        continue;
      }

      if (choice === 'ai') {
        await aiWizardPlaceholder(rl);
        continue;
      }

      if (choice === 'exit') {
        if (!dirty) {
          console.log('');
          console.log('No changes made.');
          return;
        }

        console.log('');
        const confirm = (await rl.question('Discard unsaved changes? (y/N): '))
          .trim()
          .toLowerCase();

        if (confirm === 'y' || confirm === 'yes') {
          console.log('');
          console.log('Changes discarded.');
          return;
        }

        continue;
      }

      saveEnv(values);

      console.log('');
      console.log('✓ Configuration saved');
      console.log(`  ${ENV_FILE}`);
      console.log('');
      console.log(`✓ Permissions: ${fs.statSync(ENV_FILE).mode.toString(8).slice(-3)}`);
      console.log(`✓ Storage: ${providerLabel(providerFrom(values))}`);

      if (!storageConfigured(values)) {
        console.log('⚠ Storage configuration is incomplete.');
      }

      enableAutomaticAgentMemory();

      console.log('');
      console.log('Next:');
      console.log('  toolnet-memory doctor');
      console.log('');

      return;
    }
  } finally {
    rl.close();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
