/*
 * Phase 84C — real upgrade ports.
 *
 * The imperative shell that connects the ordering rules to the machinery this
 * repository already has: disaster-recovery for the authority backup, the task
 * store for its own projection rebuild, and the daemon CLI for the build
 * barrier.
 *
 * Deliberately NOT implemented here:
 *
 *   - authority migrations. The declared registry is empty, so this adapter
 *     refuses with UPGRADE_AUTHORITY_MIGRATION_MISSING instead of inventing a
 *     rewrite for data that has no declared migration.
 *   - deleting derived stores. A derived store is regenerated by its own code
 *     path on next use; the upgrade never removes one, because a rebuild that
 *     has not run yet cannot be verified.
 */

import { spawn } from 'node:child_process';
import { existsSync, readFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { createRecoveryBackup } from '../../recovery/disaster-recovery.js';
import { reconcileSharedProjectJournal } from '../../session/shared-project-journal.js';
import { readTaskOperations, taskOperationLogPath } from '../../tasks/operation-log.js';
import { TaskStore } from '../../tasks/store.js';

import type { ProjectManifest } from '../../core/types.js';
import type { StorageProvider } from '../../storage/types.js';
import type { UpgradePorts } from './types.js';

/** Local ephemeral paths, keyed by the store kind that owns them. */
const EPHEMERAL_PATHS: Partial<Record<string, string>> = {
  task_replication_cursor: '.toolnet/tasks/replication/cursor.json',
  runtime_locks: '.toolnet/runtime/locks',
  artifact_staging: '.toolnet/cache/artifacts/staging',
};

export interface RealUpgradePortsOptions {
  project: Pick<ProjectManifest, 'id' | 'rootPath'>;
  storage?: StorageProvider;
  recoveryRoot?: string;
  /** Replace the daemon restart (tests inject a fake; production spawns the CLI). */
  restartDaemon?: () => Promise<void>;
  /** Replace the derived rebuild (tests inject a fake). */
  rebuildDerived?: (kinds: readonly string[]) => Promise<void>;
  /**
   * Replace the authority migration step.
   *
   * The declared migration registry is empty, so the default refuses. This is
   * the slot a real authority migration would be wired through — and the seam
   * the end-to-end suite uses to exercise the failure path with a REAL backup,
   * verify, rebuild and cleanup around it.
   */
  runMigration?: (migrationId: string) => Promise<void>;
  /** Replace the post-migration authority verification. */
  verifyMigration?: (migrationId: string) => Promise<boolean>;
}

function runNode(entry: string, args: readonly string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [entry, ...args], { stdio: 'ignore' });

    child.once('error', reject);

    child.once('close', (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(new Error(`daemon command exited with code ${code ?? 'unknown'}`));
    });
  });
}

/**
 * The daemon CLI as this runtime can actually reach it.
 *
 * Resolved rather than assumed: the same module runs from the production bundle
 * and from a compiled `dist/` tree, and those have different neighbours.
 */
function daemonCliEntry(): string | null {
  const here = dirname(fileURLToPath(import.meta.url));

  const candidates = [
    join(here, 'daemon-cli.js'),
    join(here, '..', 'daemon', 'cli.js'),
    join(here, '..', '..', 'daemon', 'cli.js'),
    join(here, '..', '..', '..', 'daemon', 'cli.js'),
  ];

  return candidates.find((candidate) => existsSync(candidate)) ?? null;
}

async function restartDaemonViaCli(): Promise<void> {
  const entry = daemonCliEntry();

  if (!entry) {
    throw new Error('daemon CLI entry not found; cannot enforce the build barrier');
  }

  await runNode(entry, ['restart']);
}

/**
 * Re-read the local authority stores and confirm they are still valid.
 *
 * This is the post-condition for both "authority migrated correctly" and "the
 * upgrade finished": it reads the operation log with full payload validation,
 * and re-parses the local JSON authority stores. It never repairs anything.
 */
function localAuthorityIsValid(project: Pick<ProjectManifest, 'rootPath'>): boolean {
  const log = taskOperationLogPath({ rootPath: project.rootPath } as ProjectManifest);

  if (existsSync(log)) {
    try {
      readTaskOperations(log, { repairCorruptTail: false });
    } catch {
      return false;
    }
  }

  for (const relativePath of [
    '.toolnet/project.json',
    '.toolnet/retrieval/overrides.json',
    '.toolnet/tasks/replication/cursor.json',
  ]) {
    const file = join(project.rootPath, ...relativePath.split('/'));

    if (!existsSync(file)) {
      continue;
    }

    try {
      JSON.parse(readFileSync(file, 'utf8'));
    } catch {
      return false;
    }
  }

  return true;
}

/**
 * Rebuild the derived stores that have a real, callable rebuild.
 *
 * Everything else is regenerated lazily by its own reader, which is why
 * `kinds` is accepted but only the wired kinds do work: a derived store is
 * never deleted, so leaving one stale until its next read is safe.
 */
async function rebuildDerivedFor(
  project: Pick<ProjectManifest, 'id' | 'rootPath'>,
  kinds: readonly string[]
): Promise<void> {
  for (const kind of kinds) {
    if (kind === 'task_projection') {
      new TaskStore(project as ProjectManifest).rebuildProjection();
      continue;
    }

    if (kind === 'journal') {
      reconcileSharedProjectJournal(project.rootPath);
    }
  }
}

function clearEphemeralFor(
  project: Pick<ProjectManifest, 'rootPath'>,
  kinds: readonly string[]
): void {
  for (const kind of kinds) {
    const relativePath = EPHEMERAL_PATHS[kind];

    /*
     * The daemon runtime directory is owned by the daemon itself, and the
     * in-memory test cache has no file. Both are handled by the restart phase,
     * never by deleting files out from under a running process.
     */
    if (!relativePath) {
      continue;
    }

    rmSync(join(project.rootPath, ...relativePath.split('/')), {
      recursive: true,
      force: true,
    });
  }
}

/**
 * Ports for an upgrade with no project in scope.
 *
 * A global `update` may run outside any repository. The plan is then empty
 * except for the build barrier, so only the daemon restart is reachable — and
 * anything else fails loudly rather than silently skipping authority work.
 */
export function createDaemonOnlyUpgradePorts(
  options: { restartDaemon?: () => Promise<void> } = {}
): UpgradePorts {
  const noProject = (): never => {
    throw new Error('UPGRADE_PROJECT_CONTEXT_REQUIRED');
  };

  return {
    async backupAuthority() {
      return noProject();
    },
    async runMigration() {
      return noProject();
    },
    async verifyMigration() {
      return noProject();
    },
    async rebuildDerived() {
      return noProject();
    },
    async clearEphemeral() {
      return noProject();
    },
    async restartDaemon() {
      if (options.restartDaemon) {
        await options.restartDaemon();
        return;
      }

      await restartDaemonViaCli();
    },
    /* Nothing local to re-read: the daemon restart is the whole post-condition. */
    async verifyUpgrade() {},
  };
}

export function createRealUpgradePorts(options: RealUpgradePortsOptions): UpgradePorts {
  const { project } = options;

  return {
    async backupAuthority(reason: string) {
      const manifest = await createRecoveryBackup(
        { id: project.id, rootPath: project.rootPath },
        {
          reason,
          ...(options.recoveryRoot !== undefined ? { recoveryRoot: options.recoveryRoot } : {}),
          ...(options.storage !== undefined ? { storage: options.storage } : {}),
        }
      );

      return { backupId: manifest.id };
    },

    async runMigration(migrationId: string) {
      if (options.runMigration) {
        await options.runMigration(migrationId);
        return;
      }

      /*
       * No authority migration implementation is registered. Reaching this means
       * the planner planned a migration that this build cannot execute, which is
       * a contradiction — refuse loudly rather than pretend it ran.
       */
      throw new Error(`UPGRADE_AUTHORITY_MIGRATION_MISSING ${migrationId}`);
    },

    async verifyMigration(migrationId: string) {
      if (options.verifyMigration) {
        return options.verifyMigration(migrationId);
      }

      return localAuthorityIsValid(project);
    },

    async rebuildDerived(kinds: readonly string[]) {
      if (options.rebuildDerived) {
        await options.rebuildDerived(kinds);
        return;
      }

      await rebuildDerivedFor(project, kinds);
    },

    async clearEphemeral(kinds: readonly string[]) {
      clearEphemeralFor(project, kinds);
    },

    async restartDaemon() {
      if (options.restartDaemon) {
        await options.restartDaemon();
        return;
      }

      await restartDaemonViaCli();
    },

    async verifyUpgrade() {
      if (!localAuthorityIsValid(project)) {
        throw new Error('local authority state did not verify after the upgrade');
      }
    },
  };
}
