import {
  RETRIEVAL_QUALITY_BENCHMARK,
  type RetrievalQualityBenchmarkCase,
} from './retrieval-quality-benchmark.js';

export const RETRIEVAL_QUALITY_PHASE62_BENCHMARK_VERSION = 'phase62-v2';

export const RETRIEVAL_QUALITY_ADVERSARIAL_BENCHMARK: RetrievalQualityBenchmarkCase[] = [
  {
    id: 'p62-vi-current-paraphrase',
    language: 'vi',
    question: 'việc đang làm là gì?',
    expectedMode: 'single',
    expectedIntents: ['current_work'],
    expectedSources: ['persistent-tasks'],
    tags: ['adversarial', 'paraphrase', 'current'],
  },
  {
    id: 'p62-en-current-paraphrase',
    language: 'en',
    question: 'what are we working on right now?',
    expectedMode: 'single',
    expectedIntents: ['current_work'],
    expectedSources: ['persistent-tasks'],
    tags: ['adversarial', 'paraphrase', 'current'],
  },
  {
    id: 'p62-vi-current-blocker',
    language: 'vi',
    question: 'còn vướng gì?',
    expectedMode: 'single',
    expectedIntents: ['current_work'],
    expectedSources: ['persistent-tasks'],
    tags: ['adversarial', 'paraphrase', 'current'],
  },
  {
    id: 'p62-en-current-next',
    language: 'en',
    question: 'what should I do next?',
    expectedMode: 'single',
    expectedIntents: ['current_work'],
    expectedSources: ['persistent-tasks'],
    tags: ['adversarial', 'paraphrase', 'current'],
  },
  {
    id: 'p62-vi-negated-history-current',
    language: 'vi',
    question: 'không cần lịch sử, task hiện tại là gì?',
    expectedMode: 'single',
    expectedIntents: ['current_work'],
    expectedSources: ['persistent-tasks'],
    tags: ['adversarial', 'negation', 'current'],
  },
  {
    id: 'p62-en-negated-history-current',
    language: 'en',
    question: "don't need history, what is the current task?",
    expectedMode: 'single',
    expectedIntents: ['current_work'],
    expectedSources: ['persistent-tasks'],
    tags: ['adversarial', 'negation', 'current'],
  },
  {
    id: 'p62-en-negated-history-recent',
    language: 'en',
    question: "don't use history; what is the latest state of production?",
    expectedMode: 'single',
    expectedIntents: ['recent_state'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'negation', 'recent'],
  },
  {
    id: 'p62-vi-artifact-short',
    language: 'vi',
    question: 'deploy xong chưa?',
    expectedMode: 'single',
    expectedIntents: ['artifact'],
    expectedSources: ['task-artifacts'],
    tags: ['adversarial', 'short', 'artifact'],
  },
  {
    id: 'p62-en-artifact-completed',
    language: 'en',
    question: 'has the deployment completed?',
    expectedMode: 'single',
    expectedIntents: ['artifact'],
    expectedSources: ['task-artifacts'],
    tags: ['adversarial', 'paraphrase', 'artifact'],
  },
  {
    id: 'p62-vi-artifact-report-location',
    language: 'vi',
    question: 'report JSON nằm đâu?',
    expectedMode: 'single',
    expectedIntents: ['artifact'],
    expectedSources: ['task-artifacts'],
    tags: ['adversarial', 'location', 'artifact'],
  },
  {
    id: 'p62-en-artifact-backup-path',
    language: 'en',
    question: 'where is the backup report path?',
    expectedMode: 'single',
    expectedIntents: ['artifact'],
    expectedSources: ['task-artifacts'],
    tags: ['adversarial', 'location', 'artifact'],
  },
  {
    id: 'p62-vi-rule-constraints',
    language: 'vi',
    question: 'các constraint bắt buộc của project là gì?',
    expectedMode: 'single',
    expectedIntents: ['rules'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'paraphrase', 'rules'],
  },
  {
    id: 'p62-en-rule-constraints',
    language: 'en',
    question: 'what mandatory project constraints apply?',
    expectedMode: 'single',
    expectedIntents: ['rules'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'paraphrase', 'rules'],
  },
  {
    id: 'p62-en-rule-policy-ambiguity',
    language: 'en',
    question: 'what is the deployment policy?',
    expectedMode: 'single',
    expectedIntents: ['rules'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'ambiguous', 'rules'],
  },
  {
    id: 'p62-en-decision-rationale',
    language: 'en',
    question: 'what was the rationale behind cross-host replication?',
    expectedMode: 'single',
    expectedIntents: ['decision'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'paraphrase', 'decision'],
  },
  {
    id: 'p62-vi-decision-reason',
    language: 'vi',
    question: 'lý do chọn deterministic merge là gì?',
    expectedMode: 'single',
    expectedIntents: ['decision'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'paraphrase', 'decision'],
  },
  {
    id: 'p62-vi-code-file-location',
    language: 'vi',
    question: 'TaskStore nằm file nào?',
    expectedMode: 'single',
    expectedIntents: ['code'],
    expectedSources: ['code-intelligence'],
    tags: ['adversarial', 'location', 'code'],
  },
  {
    id: 'p62-en-code-file-location',
    language: 'en',
    question: 'which file implements TaskStore?',
    expectedMode: 'single',
    expectedIntents: ['code'],
    expectedSources: ['code-intelligence'],
    tags: ['adversarial', 'location', 'code'],
  },
  {
    id: 'p62-en-code-callers',
    language: 'en',
    question: 'show callers of TaskStore',
    expectedMode: 'single',
    expectedIntents: ['code'],
    expectedSources: ['code-intelligence'],
    tags: ['adversarial', 'code'],
  },
  {
    id: 'p62-vi-history-paraphrase',
    language: 'vi',
    question: 'trước kia replication hoạt động thế nào?',
    expectedMode: 'single',
    expectedIntents: ['history'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'paraphrase', 'history'],
  },
  {
    id: 'p62-en-history-before',
    language: 'en',
    question: 'what did we do before for replication?',
    expectedMode: 'single',
    expectedIntents: ['history'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'paraphrase', 'history'],
  },
  {
    id: 'p62-en-continuity-last-agent',
    language: 'en',
    question: 'what did the last agent leave for me?',
    expectedMode: 'single',
    expectedIntents: ['continuity'],
    expectedSources: ['legacy-continuity'],
    tags: ['adversarial', 'paraphrase', 'continuity'],
  },
  {
    id: 'p62-vi-continuity-last-session',
    language: 'vi',
    question: 'session vừa rồi bàn giao gì?',
    expectedMode: 'single',
    expectedIntents: ['continuity'],
    expectedSources: ['legacy-continuity'],
    tags: ['adversarial', 'paraphrase', 'continuity'],
  },
  {
    id: 'p62-vi-recent-paraphrase',
    language: 'vi',
    question: 'production hiện giờ dùng config gì?',
    expectedMode: 'single',
    expectedIntents: ['recent_state'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'paraphrase', 'recent'],
  },
  {
    id: 'p62-en-recent-paraphrase',
    language: 'en',
    question: 'which config is production using now?',
    expectedMode: 'single',
    expectedIntents: ['recent_state'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'paraphrase', 'recent'],
  },
  {
    id: 'p62-en-summary-overview',
    language: 'en',
    question: 'give me a project overview',
    expectedMode: 'single',
    expectedIntents: ['summary'],
    expectedSources: ['persistent-tasks'],
    tags: ['adversarial', 'summary'],
  },
  {
    id: 'p62-vi-composite-semicolon',
    language: 'vi',
    question: 'task hiện tại là gì; deploy production verified chưa?',
    expectedMode: 'composite',
    expectedIntents: ['current_work', 'artifact'],
    expectedSources: ['persistent-tasks', 'task-artifacts'],
    tags: ['adversarial', 'punctuation', 'composite'],
  },
  {
    id: 'p62-en-composite-also',
    language: 'en',
    question: 'what is the current task and also which file implements TaskStore?',
    expectedMode: 'composite',
    expectedIntents: ['current_work', 'code'],
    expectedSources: ['persistent-tasks', 'code-intelligence'],
    tags: ['adversarial', 'connector', 'composite'],
  },
  {
    id: 'p62-vi-composite-newline',
    language: 'vi',
    question: 'deploy production verified chưa?\nproduction hiện giờ dùng config gì?',
    expectedMode: 'composite',
    expectedIntents: ['artifact', 'recent_state'],
    expectedSources: ['task-artifacts', 'canonical-memory'],
    tags: ['adversarial', 'punctuation', 'composite'],
  },
  {
    id: 'p62-en-composite-plus',
    language: 'en',
    question: 'what project rules apply plus what was the rationale behind append-only logs?',
    expectedMode: 'composite',
    expectedIntents: ['rules', 'decision'],
    expectedSources: ['canonical-memory'],
    tags: ['adversarial', 'connector', 'same-source'],
  },
  {
    id: 'p62-en-composite-as-well-as',
    language: 'en',
    question: 'show historical previous work for replication as well as where TaskStore is defined',
    expectedMode: 'composite',
    expectedIntents: ['history', 'code'],
    expectedSources: ['canonical-memory', 'code-intelligence'],
    tags: ['adversarial', 'connector', 'composite'],
  },
  {
    id: 'p62-vi-composite-question-separator',
    language: 'vi',
    question: 'session vừa rồi bàn giao gì? task hiện tại là gì?',
    expectedMode: 'composite',
    expectedIntents: ['continuity', 'current_work'],
    expectedSources: ['legacy-continuity', 'persistent-tasks'],
    tags: ['adversarial', 'punctuation', 'composite'],
  },
  {
    id: 'p62-vi-composite-ampersand',
    language: 'vi',
    question: 'task hiện tại là gì & deploy production verified chưa?',
    expectedMode: 'composite',
    expectedIntents: ['current_work', 'artifact'],
    expectedSources: ['persistent-tasks', 'task-artifacts'],
    tags: ['adversarial', 'connector', 'composite'],
  },
  {
    id: 'p62-vi-three-source',
    language: 'vi',
    question: 'task hiện tại là gì, deploy production verified chưa, TaskStore nằm file nào?',
    expectedMode: 'composite',
    expectedIntents: ['current_work', 'artifact', 'code'],
    expectedSources: ['persistent-tasks', 'task-artifacts', 'code-intelligence'],
    tags: ['adversarial', 'three-source', 'composite'],
  },
  {
    id: 'p62-vi-four-intent-budget',
    language: 'vi',
    question:
      'task hiện tại là gì và deploy production verified chưa và TaskStore nằm file nào và lý do chọn append-only log là gì?',
    expectedMode: 'composite',
    expectedIntents: ['current_work', 'artifact', 'code'],
    expectedSources: ['persistent-tasks', 'task-artifacts', 'code-intelligence'],
    expectedOmittedIntents: ['decision'],
    maxSources: 3,
    tags: ['adversarial', 'budget', 'three-source'],
  },
  {
    id: 'p62-en-deploy-why-not-verified',
    language: 'en',
    question: 'why is the deployment not verified yet?',
    expectedMode: 'single',
    expectedIntents: ['artifact'],
    expectedSources: ['task-artifacts'],
    tags: ['adversarial', 'ambiguous', 'artifact'],
  },
];

export const RETRIEVAL_QUALITY_PHASE62_BENCHMARK: RetrievalQualityBenchmarkCase[] = [
  ...RETRIEVAL_QUALITY_BENCHMARK,
  ...RETRIEVAL_QUALITY_ADVERSARIAL_BENCHMARK,
];
