import type { MemoryEngine } from '../core/memory-engine.js';

export class MemoryMaintenance {
  constructor(private readonly memory: MemoryEngine) {}

  run(projectId: string) {
    /*
     * 1. Remove expired transient data first so it does
     *    not participate in consolidation.
     */
    const expiredRemoved = this.memory.pruneExpired(projectId);

    /*
     * 2. Collapse repeated durable facts generated by
     *    multiple agents/sessions.
     */
    const consolidation = this.memory.consolidate(projectId);

    /*
     * 3. Existing rule/decision conflict semantics remain
     *    untouched. Old superseded records keep their
     *    retention window before deletion.
     */
    const supersededRemoved = this.memory.pruneSuperseded(projectId, 30);

    return {
      expiredRemoved,

      supersededRemoved,

      groupsConsolidated: consolidation.groupsConsolidated,

      duplicatesRemoved: consolidation.duplicatesRemoved,

      active: this.memory.list(projectId).length,

      total: this.memory.listAll(projectId).length,
    };
  }
}
